### ISSUE TITLE
Unable to Clone another private repo from the same GitHub Organization

### ISSUE THREAD

**Issue by DominicCabral** [microsoft/azure-pipelines-yaml#10]
I am currently running into an issue where I am **able** to pull from one private GitHub source in the `checkout` stage but **unable** to pull another private GitHub source from a script later in the pipeline due to lack of access rights. Note: Both Repos are a part of the same organization. And I've already connected the Azure App to GitHub with access to all Repos

Within my checkout stage I've explicitly set `persistCredentials: true` This, as I understand it, should allow the following scripts in the pipeline to use the GitHub credentials that were used in the checkout for "Get Sources".

Here is an example of the script that fails:

```
- script: |
git clone --branch=username --single-branch https://github.com/username/myRepo.git $(Agent.BuildDirectory)/myRepo
displayName: 'clone myRepo' 
```

And the output:

```
Generating script.
[command]/bin/bash --noprofile --norc /Users/vsts/agent/2.140.2/work/_temp/cb2622cc-28e0-435a-bb98-154bdabf9641.sh
Cloning into '/Users/vsts/agent/2.140.2/work/1/myRepo'...
fatal: could not read Username for 'https://github.com': Device not configured
##[error]Bash exited with code '128'
```

**Comment by astafan8** [comment]
I'm having a similar issue but it results in a different message.

I'm having a pipeline for SOME_PRIVATE_REPO that uses code from OTHER_PRIVATE_REPO within the same organization ORG. Azure Pipelines is enabled and is aware of both repositories (in settings in github).

Here's a snippet of the `azure-pipelines.yml`:
```yml
- script: |
      cd some_dir
      git clone https://github.com/ORG/OTHER_PRIVATE_REPO.git
      cd OTHER_PRIVATE_REPO
      git checkout v1
      pip install -e .
    displayName: 'Install OTHER_PRIVATE_REPO from tagged commit'
```

So, the job just hangs at the stage of ` Cloning into 'OTHER_PRIVATE_REPO'...`, and after some time gets automatically cancelled due to timeout.

I tried googling but couldn't find how to access other private github repo inside a pipeline for a private github repo. Does anybody know?

**Comment by astafan8** [comment]
I've found a solution that I don't like but it works.

In the pipelines editor on azure devops, go to variables section, and create a secret variable with a github access token in it. Then, refer to it in the `git clone` command in the `azure-pipelines.yml` file.

Resulting snippet from my yml file:
```yml
- script: |
      cd some_dir
      git clone https://x-access-token:$(astafan8-github-access-token)@github.com/ORG/OTHER_PRIVATE_REPO.git
      cd OTHER_PRIVATE_REPO
      git checkout v1
      pip install -e .
    displayName: 'Install OTHER_PRIVATE_REPO from tagged commit'
```

The `x-access-token` part was found [here](https://platform.github.community/t/git-clone-access-with-an-installation-token/486/2).

**Comment by rauljmz** [comment]
Having the exact same issue. I agree with @astafan8 - I don't like the solution with the secret and the access token. Ideally it should support multiple the build pipeline should support checkout tasks. I think it relates to this [User Voice request](https://visualstudio.uservoice.com/forums/330519-azure-devops-formerly-visual-studio-team-services/suggestions/11592954-allow-tfs-build-to-depend-on-multiple-repositories)

**Comment by Adnn** [comment]
Any progress on this front?

**Comment by Saibamen** [comment]
Moved into Developer Community: https://developercommunity.visualstudio.com/content/problem/1007491/unable-to-clone-another-private-repo-from-the-same.html
Please use "Follow" button on the right to track it

**Comment by Saibamen** [comment]
@DominicCabral:
Please go to this link and answer Microsoft team: https://developercommunity.visualstudio.com/content/problem/1007491/unable-to-clone-another-private-repo-from-the-same.html
