### ISSUE TITLE
.vsts-ci.yml does not create a build definition for new projects

### ISSUE THREAD

**Issue by Glober777** [microsoft/azure-pipelines-yaml#100]
I've noticed, that if I create a new project in Azure DevOps and initialize it using my existing local git repo which includes '.vsts-ci.yml' file, a build definition doesn't get created automatically and in order to trigger one to be created I need to make some changes to the file and push those changes up to the origin.

The thing is that I have the '.vsts-ci.yml' file inside of my project template and I'd really like it to automatically generate the build definition straight on the initial push (so that I could then go and configure branch policies for the master to depend on this build).

Is this an expected behavior or it's actually a bug?

Thanks!

**Comment by bryanmacfarlane** [comment]
We watch for the yaml file on push

**Comment by Glober777** [comment]
@bryanmacfarlane, does that include the initial push of the local repo?

**Comment by Glober777** [comment]
Any news on this? I can reliably reproduce this issue every time I initialize a new project.

**Comment by samuel-weber** [comment]
Same problem... any work around?

**Comment by ahoefling** [comment]
This started affecting us as well. We have hundreds of projects that all use .vsts-ci.yml and this is causing confusion across our org. 

## Our Workaround

1. Create `.azure-pipelines.yml` in the repo and push
2. Verify the build was scaffolded correctly
3. Rename `.azure-pipelines.yml` to `.vsts-ci.yml`
4. Open up Azure Pipelines and edit the Pipeline Settings
5. Rename the YAML File Path to `.vsts-ci.yml`

This is quite a manual effort to use the old convention. Is it possible to make this configurable

**Comment by azurenative** [comment]
Hi, is this issue still on ? i'm also still not able to create automatically the build pipeline.
Even apply the workaround, it does not work.
New project, empty repo, created the file and pushed.
