### ISSUE TITLE
Regex Azure DevOps Build Variables

### ISSUE THREAD

**Issue by andrewsuiter** [microsoft/azure-pipelines-yaml#101]
Is it possible to regex a build variable? 

ex: $(System.TeamProject) = TEAM1-TestProject

I would like get anything to the left of the hyphen 'TEAM1'. Is this possible?

**Comment by staff0rd** [comment]
I'd like to use something similar to get just `$(Rev:r)` out of `$(Build.BuildNumber)` considering it's not otherwise available.

**Comment by jpreese** [comment]
Would also be interested in this for getting specific regex groups out of `SourceBranchName`for use in tagging schemes.
