### ISSUE TITLE
Unable to checkout external repo

### ISSUE THREAD

**Issue by samiyaakhtar** [microsoft/azure-pipelines-yaml#103]
Even though [docs](https://github.com/Microsoft/azure-pipelines-yaml/blob/master/design/pipeline-resources.md#example) state that the checkout function allows cloning a secondary repo, when I try running a simple pipeline to push to a secondary repo which is within the same user account, I get this error `Checkout of repository 'destinationRepo' is not supported. Only 'self' and 'none' are supported.`

Here's the code I'm trying to test with:
```

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

resources:         
  repositories:
  - repository: destinationRepo
    type: github
    name: samiyaakhtar/solid-doodle
    endpoint: solid-doodle-push-auth

steps:
- checkout: destinationRepo
  persistCredentials: true
  clean: true

- powershell: |
   git --version
   git checkout master
   git config user.email "me@test.ca"
   git config user.name "AzureDevOps Bot"
   Write-Host "git commit with message"
   git commit  --allow-empty -a -m "Test Commit from Azure DevOps"
   Write-Host "git push"
   git push

```

**Comment by ngnkm** [comment]
Hello.
Did you get a solution about this error?
Please let me know if that is the case. 
Thanks

**Comment by samiyaakhtar** [comment]
Nope this `checkout` step from azure-pipelines for an external repo doesn't work and their documentation is clearly messed up. Instead I ended up doing a manual `git clone` step through a shell script.

**Comment by samiyaakhtar** [comment]
Nope this `checkout` step from azure-pipelines for an external repo doesn't work and their documentation is clearly messed up. Instead I ended up doing a manual `git clone` step through a shell script.

**Comment by ngnkm** [comment]
thanks for your response. Now I'm trying to clone my repo via a git clone command but the authorization failed. How did you configure it? I used this command but it's doesn't work. ` git -c http.https:*******/_git/*****.extraheader="AUTHORIZATION: bearer *******" clone https:*****/_git/**** --branch master`

**Comment by djee-ms** [comment]
Bump - Is there any plan/timeline to support this feature? This would be much easier than doing some manual git clone with custom PAT-based authorization, which is always tricky to get right and safe. Also the documentation should be updated to not advertise the feature if it is not implemented.

**Comment by djee-ms** [comment]
For completeness and @ngnkm if you still have issues, the workaround is correct but:
- the command can be simplified into `git -c http.extraheader=... clone -b master` since the extra header will apply only to the current command so no need to specify a particular remote host
- you can also use the extraheader `Authorization: Basic <token>` and generate the token based on a username and a personal access token (PAT), for example with the PowerShell command:
  ```powershell
  $Authorization = "Authorization: Basic " + [System.Convert]::ToBase64String([System.Text.Encoding]::UTF8.GetBytes('$(User):$(PAT)'))
  git clone -c http.extraheader="$Authorization" -b master $(RepoURL) $(Build.SourcesDirectory)/extra_repo
  ```
  This has the advantage of working with a GitHub repository. You can generate a PAT in your GitHub account settings.

**Comment by JamesDLD** [comment]
The "self" option on the checkout's task permits to checkout the repo where the initial Pipelines YAML file was found.
You currently can't replace this option with the name of your repo.
At the time speaking if you want to checkout your github repo with the "checkout" task you need to move your YAML file on your github repo.

Multi-repository support for YAML pipelines is planned for Q3 2019 in Azure DevOps roadmap and this might solve your issue, stay tunned : [Azure DevOps Roadmap Q3 - ITEM 1454026](https://dev.azure.com/mseng/AzureDevOpsRoadmap/_workitems/edit/1454026)

**Comment by djee-ms** [comment]
Thanks @JamesDLD. In that case can you please fix the Azure Pipeline YAML documentation which currently suggests this feature is already implemented, as noted by @samiyaakhtar?

**Comment by JamesDLD** [comment]
Hello @djee-ms,
The documentation about the "checkout" task explains what I have written in my upper comment, I don't see any wrong suggestion : 
<img width="1051" alt="image" src="https://user-images.githubusercontent.com/18073917/62423654-763b8180-b6c3-11e9-9813-b1b40381e386.png">

Ps : I'm not working at Microsoft, If you see any documentation error feel free to open a ticket.

**Comment by JamesDLD** [comment]
Indeed the doc highlighted by @samiyaakhtar [here on GitHub](https://github.com/Microsoft/azure-pipelines-yaml/blob/master/design/pipeline-resources.md#example) shows that we can use other parameters that "none" or "self" in the "checkout" task..
This is probably being released, hopefully!
Note that I am not working at Microsoft about your ask about updating MS doc.

**Comment by djee-ms** [comment]
Ok sorry @JamesDLD I didn't check you profile.
The docs points by @samiyaakhtar is the `master` branch, maybe we're too early and the feature is being rolled out but didn't make it to prod yet. That would be consistent with the roadmap you linked.

**Comment by fraserdarwent** [comment]
Ran into the same issue. Docs definitely misleading.

**Comment by zufengxu** [comment]
same issues here, not sure the document says about and even give instruction on features that are not there.

**Comment by michaelw85** [comment]
I was running into similar issues trying to use ARM templates from a different repo in my multistage yaml pipeline.

I managed to clone the dependent repo using the header info from the repo you are currently using. 
```yml
      - checkout: self
        clean: true
        persistCredentials: true

      - powershell: |
          $extraheader = git config http.https://<USER>@dev.azure.com/<COMPANY>/Cloud/_git/<CURRENT_REPO(self)>.extraheader
          git clone -c http.extraheader="$extraheader" --depth 1 --branch ${{ parameters.branch }} ${{ parameters.repo }}
        displayName: Git clone
        workingDirectory: $(Build.SourcesDirectory)
```

**Comment by djee-ms** [comment]
Yes but this is very annoying and error prone. Your case is quite simple @michaelw85, so your solution works here. But things get complicated fast when cloning repositories with submodules for example, or when trying to optimize checkout of a particular commit for large repos like the built-in checkout does. Also some hosts like GitHub don't support checking out random commits, only refs, so you need a more complex series of commands.

Also incidentally git commands output to `stderr`, which powershell assumes are errors, so you should make sure to handle that to avoid spurious failures. See again the built-in checkout. There is a flag `failOnStderr` on the powershell task, but it doesn't work for me. So I ended up wrapping all my git commands with a PS function call capturing `stderr` and checking the exit code instead for errors. My checkout script is now 50 lines or so.

All of that to say, this could be handled by the built-in checkout, probably should for the sake of users, and hopefully will be soon as @JamesDLD  pointed.

**Comment by djee-ms** [comment]
I just found [that doc](https://github.com/microsoft/azure-pipelines-yaml/blob/master/design/multicheckout.md) which very clearly says this is supported and details the steps to configure multiple repositories. I am assuming this is not rolled out yet?

**Comment by andreujuanc** [comment]
I can't even do checkout:self, i get ""Checkout of multiple repositories is not supported."
Troubleshoot".
I think priority for this work item should be increased, checking out multiple repos is a must.

**Comment by graham768** [comment]
Looks like this feature is still in development for Q4, but I found some more official documentation for a workaround if anyone is still struggling with this before the release comes
https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/pipeline-options-for-git?view=azure-devops#clone-a-second-repo

**Comment by drdamour** [comment]
The recent DevOps rollout has this multi checkout natively supported now and docs seemed updated...so I think this can be closed

however if u came here looking for some secret sauce like me for something like tricking terraform to use the pipelines creds when importing modules from other DevOps repos in your project the secret is in this thread...kinda.  The hint about PATs is good for non DevOps repos but if you are in DevOps repos there’s an easier command from 
https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/azure-repos-git?view=azure-devops&tabs=yaml#authorize-access-to-your-repositories

‘git clone -c http.extraheader="AUTHORIZATION: bearer $(System.AccessToken)" <clone URL> ’

So the secret is that variable pipelines injects no need to generate it yourself.  I passed that to terraform (via global git config trickery)

**Comment by ericycs** [comment]
> The recent DevOps rollout has this multi checkout natively supported now and docs seemed updated...so I think this can be closed
> 
Not working on my devops org yet

**Comment by drdamour** [comment]
> > The recent DevOps rollout has this multi checkout natively supported now and docs seemed updated...so I think this can be closed
> 
> Not working on my devops org yet.
> Getting error:
> Checkout of repository 'otherRepo' is not supported. Only 'self', 'none', or a repository alias are supported.

U setup that alias in the resources section per the docs?

**Comment by ericycs** [comment]
> > > The recent DevOps rollout has this multi checkout natively supported now and docs seemed updated...so I think this can be closed
> > 
> > 
> > Not working on my devops org yet.
> > Getting error:
> > Checkout of repository 'otherRepo' is not supported. Only 'self', 'none', or a repository alias are supported.
> 
> U setup that alias in the resources section per the docs?

Found the issue. Doesn't work in deployment job. Will be fixed in 3 week in next rollout as per this issue item:
https://github.com/MicrosoftDocs/vsts-docs/issues/6683

**Comment by nbfva1** [comment]
The checkout: self works fine but a checkout: myrepo , defined in a resources: list fails with  `fatal: repository 'myrepo...' not found`

The url shown in line 20 is correct and  works with a manual git clone etc

![image](https://user-images.githubusercontent.com/32124657/72896541-4ab75c80-3d20-11ea-8010-4d1d1dcd6ca9.png)

**Comment by Saibamen** [comment]
Moved into Developer Community: https://developercommunity.visualstudio.com/content/problem/1007479/unable-to-checkout-external-repo.html
Please use "Follow" button on the right to track it

**Comment by Saibamen** [comment]
@samiyaakhtar: Please go to this link and check if this issue is still happen: https://developercommunity.visualstudio.com/content/problem/1007479/unable-to-checkout-external-repo.html

**Comment by samiyaakhtar** [comment]
@saibamen seems to be working now, thanks!

**Comment by airowe** [comment]
Getting this error now. Is it a versioning issue?

**Comment by gswallow** [comment]
I have a Terraform project that calls another module in a private github repository.  Do I still have to do this?

```
  - checkout: self
    clean: true
    persistCredentials: true
  - task: Bash@3
    name: Add_Git_Credentials_to_Global_ExtraHeader_Config
    displayName: Add Git Credentials to http.extraheader
    inputs:
      targetType: inline
      script: |
        origin=$(git config remote.origin.url)
        origin=${origin%.git}
        git config --global http.extraheader "$(git config http.${origin}.extraheader)"
```
