### ISSUE TITLE
Adding a manual trigger for a build step

### ISSUE THREAD

**Issue by CecileRobertMichon** [microsoft/azure-pipelines-yaml#117]
Hi, 

My team is migrating from circle CI to Azure DevOps and so far our experience has been good. However, there is one thing we were able to do with circle that we don't know how to do with pipelines and that is how to add a manual trigger for PR E2E build job. This is the previous definition we had for circle:
https://github.com/Azure/aks-engine/blob/master/.circleci/config.yml#L309

Basically, since the tests deploy Azure resources on our subscriptions, we'd like to be able to control when PRs are able to run the tests. So that would be either having a manual approval step that can only be approved by code owners, or only triggering the pipeline when a certain label is present on the PR (such as "ok-to-test"). Do you know if there are any existing ways to achieve this scenario with Azure DevOps builds and, if not, could you please consider this feature request?

**Comment by davidtom** [comment]
Hi,

My team would love to see this feature as well. It looks like it exists for [release pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/manual-intervention?view=azure-devops), but not build pipelines. And almost certainly not YAML build pipelines...

Any updates or comments on this?

**Comment by CecileRobertMichon** [comment]
@davidtom my team was able to workaround our issue using https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/github?view=azure-devops&tabs=yaml#comment-triggers

**Comment by davidtom** [comment]
@CecileRobertMichon this looks promising, thank you!

**Comment by jPrest** [comment]
We are currently migrating from GitlabCI and this feature is missing for my team aswell.

**Comment by saurabh-deep** [comment]
+1

We also need this functionality of manually triggering a build step.

**Comment by rumax** [comment]
Any progress with this issue? Will it be implemented and when?

**Comment by FabienTaillon** [comment]
Same here, using several other CI tools, and Azure DevOps is the only one where I couldn't find how to achieve this.

**Comment by amartin1911** [comment]
GitLab has it. Why not Azure DevOps? Please add manual triggers

**Comment by YEMEAC** [comment]
💯

**Comment by vijayma** [comment]
You can trigger a pipeline manually. I believe what is being asked here is to be able to start a stage inside a pipeline manually. That capability exists in classic releases but not in YAML pipelines yet. That work is planned but we do not have an ETA yet.

**Comment by shashban** [comment]
A quick clarification on the scope of the problem we are discussing. 
I assume this is a pipeline with multiple stages, with one of them being the build or the PR stage. There are other deploy stages dependent on these stages in the pipeline.
We are talking about how to manually start the build stage. 

Can we assume the scenario is that the build stage has not run at all so far and we are looking to start it immediately? If we did not manually start now, then it would run at some point of time based on conditions. We are looking to short circuit the pipeline.

**Comment by Saibamen** [comment]
Moved into Developer Community: https://developercommunity.visualstudio.com/idea/1007478/adding-a-manual-trigger-for-a-build-step.html
Please use "Follow" button on the right to track it
