### ISSUE TITLE
Can't use vsdevcmd entrypoint in azure pipelines container images

### ISSUE THREAD

**Issue by devhawk** [microsoft/azure-pipelines-yaml#119]
I'm trying to use pipelines for container builds on Windows. My goal is to launch the pipeline steps inside a VS devloper command prompts provided by VS DevTools. I tried using the ENTRYPOINT/CMD settings from the [official docs](https://docs.microsoft.com/en-us/visualstudio/install/build-tools-container?view=vs-2017). I can launch the container locally no problem, but my pipeline fails on the build step (logs below).

I suspect this is user error, but if so there need to be official Pipeline docs that explain how to use container builds on Windows with the developer command prompt.

Azure Pipeline log:
```
2019-02-05T21:41:08.8214628Z ##[section]Starting: CmdLine
2019-02-05T21:41:08.8315751Z ==============================================================================
2019-02-05T21:41:08.8315874Z Task         : Command Line
2019-02-05T21:41:08.8315918Z Description  : Run a command line script using cmd.exe on Windows and bash on macOS and Linux.
2019-02-05T21:41:08.8315962Z Version      : 2.146.1
2019-02-05T21:41:08.8316044Z Author       : Microsoft Corporation
2019-02-05T21:41:08.8316085Z Help         : [More Information](https://go.microsoft.com/fwlink/?LinkID=613735)
2019-02-05T21:41:08.8316146Z ==============================================================================
2019-02-05T21:41:08.9743007Z Error response from daemon: Container 9baa9dea223be969857b9b5d85cb7343b4aa68bc77e7432e5aa2c348c84c2259 is not running
2019-02-05T21:41:09.1014069Z ##[error]Exit code 1 returned from process: file name 'C:\Program Files\Docker\docker.EXE', arguments 'exec -i 9baa9dea223be969857b9b5d85cb7343b4aa68bc77e7432e5aa2c348c84c2259 C:\__a\externals\node\bin\node.exe C:\__w\_temp\containerHandlerInvoker.js'.
2019-02-05T21:41:09.1036809Z ##[section]Finishing: CmdLine
```

azure-pipelines.yaml:
``` yaml
resources:
  containers:
  - container: build_container
    image: devhawk/win-buildtools-entrypoint
    
pool:
  vmImage: 'win1803'

container: build_container

steps:
- script: set
```

devhawk/win-buildtools-baseline Dockerfile:

>note, I've split my build container image into two docker files so I can experiment with changing the entrypoint settings without having to push the build tools layer every time
``` Dockerfile
# escape=`

FROM mcr.microsoft.com/windows/servercore:1803

ADD https://aka.ms/vs/15/release/vs_buildtools.exe C:\TEMP\vs_buildtools.exe

RUN C:\TEMP\vs_buildtools.exe --quiet --wait --norestart --nocache `
    --add Microsoft.VisualStudio.Workload.VCTools `
    --add Microsoft.VisualStudio.Component.Windows10SDK.17763 `
    --add Microsoft.VisualStudio.Component.VC.CMake.Project `
    --add Microsoft.VisualStudio.Component.VSSDKBuildTools `
    --add Microsoft.VisualStudio.Component.VC.ATL `
    --add Microsoft.Net.Component.4.6.1.SDK `
    --remove Microsoft.VisualStudio.Component.Windows10SDK.10240 `
    --remove Microsoft.VisualStudio.Component.Windows10SDK.10586 `
    --remove Microsoft.VisualStudio.Component.Windows10SDK.14393 `
    --remove Microsoft.VisualStudio.Component.Windows81SDK `
    --installPath C:\BuildTools
```

devhawk/win-buildtools-entrypoint Dockerfile:
``` Dockerfile
# pushed to docker hub as devhawk/win-buildtools-entrypoint

FROM devhawk/win-buildtools-baseline

# Start developer command prompt with any other commands specified.
ENTRYPOINT C:\BuildTools\Common7\Tools\VsDevCmd.bat &&
CMD ["cmd.exe"]
```

**Comment by vtbassmatt** [comment]
@devhawk sorry I missed this. Can you include additional logs, specifically the ones from when Azure Pipelines spins up the container? Something went wrong at startup, so by the time it gets to the script step, that's bound to fail.

**Comment by devhawk** [comment]
[logs_27.zip](https://github.com/Microsoft/azure-pipelines-yaml/files/2865846/logs_27.zip)

**Comment by vtbassmatt** [comment]
That's really odd. The container didn't show any signs of trouble at startup, and we spin it down at the end. @TingluoHuang I don't have admin on the -agent repo, so I can't move this issue, but it seems like a bug. Thoughts?

**Comment by cor3ntin** [comment]
I experience the exact same issue

**Comment by cor3ntin** [comment]
@vtbassmatt I don't know who are the people I should reach out to, so can you convey to microsoft teams that, forcing to users to use the developer community website instead of GitHub for issues reporting is  a big regression in terms of communicating with your users?

That website has a bad UX, is full of bugs (the text editor is a bad joke from 2005), not tied to GitHub in anyway and provide little useful information as, unsurprisingly, Microsoft employees like it as much as the rest of us.


Thanks.

**Comment by Saibamen** [comment]
Moved into DC: https://developercommunity.visualstudio.com/content/problem/1008354/cant-use-vsdevcmd-entrypoint-in-azure-pipelines-co.html
Use Follow button on the right to track

**Comment by Saibamen** [comment]
@devhawk: Please go to this link and answer Microsoft team: https://developercommunity.visualstudio.com/content/problem/1008354/cant-use-vsdevcmd-entrypoint-in-azure-pipelines-co.html

**Comment by devhawk** [comment]
@Saibamen I've long since moved on to a new project (and left MSFT). You can circle w/ the folks from http://github.com/microsoft/xlang to see if they are still need this.

**Comment by Saibamen** [comment]
I added dumb issue with links to notify XLang team: https://github.com/microsoft/xlang/issues/642

**Comment by DefaultRyan** [comment]
Thanks. We're not actively using that feature right now. Feel free to close.
