### ISSUE TITLE
Define variables in steps

### ISSUE THREAD

**Issue by rylev** [microsoft/azure-pipelines-yaml#131]
It would be nice to be able to define variables in individual steps. It is possible to define environment variables, but then one has to worry about how those env variables are expanded. I've worked around this by defining a variable for the entire job, but it would be cleaner to be able to only scope that particular variable to the one step that needs it.

**Comment by wichert** [comment]
This would be very useful for me as well. My use case is determining the version number for a tag in a monorepo, and using that to get a docker image. For example I have a monorepo that looks like this:

```
- lerna.json
- package.json
- packages/A/...
- packages/B/...
```

Tags for release of A look like `A/1.2.3`, and tags for B look like `B/1.2.3`. Currently there is no way to extract the version from the tag name and pass that to Docker@2 / buildAndPush.
