### ISSUE TITLE
How to check each command in a multi-line script for failure

### ISSUE THREAD

**Issue by phil-opp** [microsoft/azure-pipelines-yaml#135]
My problem is that the following multi-line script does not cause a failure:

```yaml
- script: |
    false
    true
```

I tried to work around this by using `set -e` and `set -o pipefail`, but this does not work on windows.

I can only think of two workarounds to get the desired behavior:

- Split the multi-line script into multiple single-line scripts. This is ugly, because it clutters the pipeline with lots of micro-tasks and does not work when switching directories.
- Use `bash` instead of `script`, so that `set -e` is also available on windows. However, I want to ensure that my project also runs on the native `cmd`.
- Use the `failOnStandardError` option to fail when anything is printed to stderr. However, this also fails when the Rust compiler emits a warning, which is not what I want in this case.

None of these workarounds seem like a good solution to me, as they all have clear problems or disadvantages. Is there any proper solution for this?

I think this behavior is somewhat dangerous as it can lead to broken code if one does not check the output manually. A safe default (i.e. fail on error) and an option to change that default would be a better choice in my opinion.

The same issue was reported earlier in https://github.com/Microsoft/azure-pipelines-agent/issues/1803.

**Comment by escalonn** [comment]
the default behavior chosen here is nuts, but evidently that ship has sailed.
there needs to be a step option for this, to set both `errexit` and `pipefail` flags in one option.
