### ISSUE TITLE
vmImage incorrect in generated yaml from existing pipeline

### ISSUE THREAD

**Issue by charlesbetros** [Microsoft/azure-pipelines-yaml#137]
vmImage is using the Agent Pool name (Hosted VS2017) instead of the correct name (vs2017-win2016 in this case). I can create the pipeline from the generated yaml, but it fails to build until I update the image name.

![1-pipeline-settings](https://user-images.githubusercontent.com/11257591/53818966-a32a1380-3f2e-11e9-97be-a2fa4857c48c.png)

![2-agent-job-view-yaml](https://user-images.githubusercontent.com/11257591/53818993-afae6c00-3f2e-11e9-9399-d0a974028b5f.PNG)

**Comment by DavidStaheli** [comment]
@charlesbetros, thank you for reporting this.  It has been fixed and, fingers crossed, should reach all stages of production this week.
# 🤞
