### ISSUE TITLE
Missing YAML option to checkout submodules recursively

### ISSUE THREAD

**Issue by sschuberth** [Microsoft/azure-pipelines-yaml#153]
While it seems that the general feature to checkout submodules recursively [has been added to the agent](https://github.com/Microsoft/azure-pipelines-agent/pull/887), there does not seem to be a YAML option to actually enable it. Just setting

```
steps:
- checkout: self
  submodules: true
```

does *not* checkout submodules recursively as can bee seen [here](https://dev.azure.com/sschuberth/oss-review-toolkit/_build/results?buildId=15&view=logs&jobId=12f1170f-54f2-53f3-20dd-22fc7dff55f9&taskId=af08acd5-c28a-5b03-f5a9-06f9a40627bb&lineStart=321&lineEnd=322&colStart=1&colEnd=1).

**Comment by TingluoHuang** [comment]
https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema#checkout

`submodules: recursive`

**Comment by sschuberth** [comment]
Ah, thanks! Strange how I could have overlooked that. Closing this!

**Comment by AndersBillLinden** [comment]
> While it seems that the general feature to checkout submodules recursively [has been added to the agent](https://github.com/Microsoft/azure-pipelines-agent/pull/887), there does not seem to be a YAML option to actually enable it. Just setting
> 
> ```
> steps:
> - checkout: self
>   submodules: true
> ```
> 
> does _not_ checkout submodules recursively as can bee seen [here](https://dev.azure.com/sschuberth/oss-review-toolkit/_build/results?buildId=15&view=logs&jobId=12f1170f-54f2-53f3-20dd-22fc7dff55f9&taskId=af08acd5-c28a-5b03-f5a9-06f9a40627bb&lineStart=321&lineEnd=322&colStart=1&colEnd=1).

Broken link
