### ISSUE TITLE
Move stages/environments out of releases

### ISSUE THREAD

**Issue by hbuckle** [microsoft/azure-pipelines-yaml#157]
Currently stages are baked into a release when it is created and new stages cannot be added to an existing release - this causes problems when we want to deploy a release to a stage that did not exist at the time the release was created.
The only option is to add the new stage to the release definition and then create a new release using the same artifacts. This breaks the principle that we should be able to look at a release and see all of the stages it has been deployed to.
Also, by creating a new release with the old artifacts, there is no guarantee the release definition has not changed and the new release may no longer work to deploy the old artifacts.

The short term solution would be to allow adding a new stage to an existing release. Even better would be to make stages their own entities that exist outside of releases at the project level, then any release can be deployed to any stage at any time.

The current implementation assumes we know in advance every environment we will ever have, which is simply not possible.

**Comment by samuel-begin** [comment]
I would love to see the yaml releases feature which would help solve this issue!
