### ISSUE TITLE
Setting OutputVariables in YAML

### ISSUE THREAD

**Issue by mmajcica** [microsoft/azure-pipelines-yaml#170]
Some of the tasks do allow us to specify the Output variables, as Download Secure File Task,

![image](https://user-images.githubusercontent.com/3026551/55945746-b0cc6a80-5c4b-11e9-8273-5651f8563c8e.png)

How do we specify these values in our YAML file?

**Comment by mloskot** [comment]
This doesn't help? https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables
