### ISSUE TITLE
yaml: support yaml anchors

### ISSUE THREAD

**Issue by flokli** [microsoft/azure-pipelines-yaml#187]
[anchors and merge keys](https://camel.readthedocs.io/en/latest/yamlref.html#merge-keys) are [part of the yaml spec](https://yaml.org/spec/1.2/spec.html#id2765878), would allow some sort of boilerplate deduplication, and it's really annoying azure pipelines yaml only supports a subset of yaml:

> /azure-pipelines.yml: Anchors are not currently supported. Remove the anchor 'SLACK'

 Please add support for it.

references:
 - https://github.com/Microsoft/azure-pipelines-yaml/pull/46#issuecomment-437073818
 - https://github.com/digital-asset/daml/pull/560#discussion_r279126549

**Comment by SeWieland** [comment]
This is still an open and valid issue

**Comment by Cynnexis** [comment]
There is a similar issue in the Developer Community forum: [Add support for YAML anchors and merge keys in pipelines](https://developercommunity.visualstudio.com/t/Add-support-for-YAML-anchors-and-merge-k/959278)
However, it has not been updated since 2020.
