### ISSUE TITLE
How to use array variable in YAML build?

### ISSUE THREAD

**Issue by SupporterMan** [microsoft/azure-pipelines-yaml#188]
How can we pass a array variable in YAML build?

Following is my sample YAML build with template:
my-template.yml:
`parameters:
 projects: []
steps:
- ${{ each project in parameters.projects }}:
  - script: "echo 3 ${{ project }}"`

ci.yml:
`steps:
- template: my-template.yml
  parameters:
   projects: ["Test1", "Test2"]`

Above sample works fine. It will add two script task to output Test1 and Test2.
But if I define a projects as a variable with value '"Test1", "Test2"', it will output a string as below shows.
ci.yml:
`steps:
- template: my-template.yml
  parameters:
   projects: [$(projects)]`

output:
3 "Test1", "Test2"

**Comment by MalcolmMcNeely** [comment]
@SupporterMan Did you find a resolution for this issue?

**Comment by jzelos** [comment]
I recently had to combine two string using join and an array. In order to achieve that I created an array variable using the following syntax (indented and line separated) to create it. 

```
variables: 
  versionParts:
    $(Build.BuildNumber)
    $(system.pullRequest.sourceBranch)
```

**Comment by sxmartin** [comment]
Was there a solution prescribed for this?
