### ISSUE TITLE
Comments in steps.bash break variables set with task.setvariable (trailing apostrophe)

### ISSUE THREAD

**Issue by mloskot** [microsoft/azure-pipelines-yaml#193]
_(This bug report may as well belong to https://github.com/Microsoft/azure-pipelines-tasks/, I'm not sure.)_

I'm having a strange problem where `##vso[task.setvariable variable=...]` called in `steps.bash` randomly outputs variable value with trailing apostrophe.
I have managed to reproduce the problem with MWE which is available hre

* Config: https://github.com/mloskot/ci-test/tree/ml/azp-setvariable-task-bug
* Build: https://dev.azure.com/mloskot/ci-test/_build/results?buildId=280

I'm copying the important bits below. Here is my `azure-pipelines.yml` or `.azure-pipelines.yml`:

```
trigger:
  branches:
    include:
    - develop
    - master
    - bugfix/*
    - feature/*
    - fix/*
    - ml/*
    - pr/*

stages:
- stage: Test
  jobs:
  - job: 'Linux'
    pool:
      vmImage: 'ubuntu-16.04'
    strategy:
      matrix:
        GCC 5:
          TOOLSET: gcc-5
    steps:
    - bash: |
        set -e
        source install.sh
        echo "step install - original SELF       before task.setvariable: SELF=$SELF"
        echo "step install - original BOOST_ROOT before task.setvariable: BOOST_ROOT=$BOOST_ROOT"
        # AzP predefines BOOST_ROOT, so we need this gymnastics to override it with ours.
        # AzP requires to run special task in order to export
        # BOOST_ROOT and others as job-scoped variable from a script.
        #
        echo "SELF=$SELF"
        echo "BOOST_ROOT=$BOOST_ROOT"
        # Comment
        echo "##vso[task.setvariable variable=SELF]$SELF"
        echo "##vso[task.setvariable variable=BOOST_ROOT]$BOOST_ROOT"
        # Comment
        echo "##vso[task.setvariable variable=SELF1]$SELF"
        echo "##vso[task.setvariable variable=BOOST_ROOT1]$BOOST_ROOT"
        #
        echo "##vso[task.setvariable variable=SELF2]"$SELF
        echo "##vso[task.setvariable variable=BOOST_ROOT2]"$BOOST_ROOT
      displayName: 'Install'
    - bash: |
        set -e
        echo "step build - overriden: SELF=$SELF"
        echo "step build - overriden: BOOST_ROOT=$BOOST_ROOT"
        echo "step build - variant 1: SELF1=$SELF1"
        echo "step build - variant 1: BOOST_ROOT1=$BOOST_ROOT1"
        echo "step build - variant 2: SELF2=$SELF2"
        echo "step build - variant 2: BOOST_ROOT2=$BOOST_ROOT2"
        ls $BOOST_ROOT
        ls $BOOST_ROOT1
        ls $BOOST_ROOT2
      displayName: 'Build'
```

The important part are comments in the first `steps.bash` section:

```
#
echo "SELF=$SELF"
echo "BOOST_ROOT=$BOOST_ROOT"
# Comment
echo "##vso[task.setvariable variable=SELF]$SELF"
echo "##vso[task.setvariable variable=BOOST_ROOT]$BOOST_ROOT"
# Comment
echo "##vso[task.setvariable variable=SELF1]$SELF"
echo "##vso[task.setvariable variable=BOOST_ROOT1]$BOOST_ROOT"
#
echo "##vso[task.setvariable variable=SELF2]"$SELF
echo "##vso[task.setvariable variable=BOOST_ROOT2]"$BOOST_ROOT
```

The random aspect is that depending on how I shuffle the comment, leave just `#` or `# some text`, values of the variables exported with the `task.setvariable` will get trailing apostrophe garbage as shown here:

![image](https://user-images.githubusercontent.com/80741/57179199-6ec5cb80-6e7b-11e9-96f4-0155b380cc76.png)

The issue is that the values of the variables include the trailing apostrophe:

```
BOOST_ROOT=/home/vsts/work/1/s/boost-root'
BOOST_ROOT1=/home/vsts/work/1/s/boost-root'
BOOST_ROOT2=/home/vsts/work/1/s/boost-root'
```

I hit this annoying issue while working on a larger `azure-pipelines.yml` for one of Boost C++ libraries.

Today, it took me ~50 tries and builds to reproduce it. Initially, I thought it may be related to use of `set -e` or `set -ex` in `steps.bash` and `*.sh` scripts called in YAML. No, it does not seem to be a problem.

Then, I thought it may be related to the two syntaxes of invoking `task.setvariable` from Bash, that is either of:
```
echo "##vso[task.setvariable variable=SELF]$SELF"
echo "##vso[task.setvariable variable=SELF]"$SELF
```
No, this does not seem to be the problem.

I'm fairly convinced the problem is with using `#` comments in `steps.bash`. It seems the YAML is not parsed correctly and this confuses parsing of the double-`#` in `##vso[task.setvariable`. I'm guessing, but I have to admit given time I wasted to figure this out, it is a properly annoying bug.

**Comment by mloskot** [comment]
I've found this is a known problem!
According to this guide https://docs.microsoft.com/en-us/azure/devops/pipelines/troubleshooting#variables-having--single-quote-appended

In Bash, the issue is affected by `set -x` indeed!

-----

In Windows variant of `steps.script` that run CMD, similar also hits if one uses

```
echo "##vso[task.setvariable variable=SELF]%SELF%"
echo "##vso[task.setvariable variable=BOOST_ROOT]%BOOST_ROOT%"
```

Then, trailing `"` is appended.

To avoid this, the double quotes around the task need to be removed:

```
echo ##vso[task.setvariable variable=SELF]%SELF%
echo ##vso[task.setvariable variable=BOOST_ROOT]%BOOST_ROOT%
```

-----

Although I understand this is documented as a known issue (for Bash **only** though), parsing of the tasks needs to be fixed. Clearly, this is not a problem with `set -x` only in Bash. Something wrong is happening around parsing of the YAML.
This is causing lots of annoying issues that waste huge amount of time.

**Comment by wez** [comment]
I also wasted a couple of hours on this issue today.  Part of the problem is that the `##vso` stuff is invisible when viewing the job output, so we simply have no idea what is going on, which makes things very frustrating.

**Comment by marcinma** [comment]
It may happen randomly when changing `script` to `bash` , sometimes changing uppercase to lowercase also affects apostrophe
