### ISSUE TITLE
External Git with yaml

### ISSUE THREAD

**Issue by virzak** [microsoft/azure-pipelines-yaml#200]
Are there plans to introduce yaml pipelines support for external (other) git, which is currently [not supported](https://developercommunity.visualstudio.com/content/problem/379285/create-build-pipeline-from-azure-pipelinesyml-with.html)?

Since yaml is the preferred pipeline method for large projects, it would be nice to know that switching to yaml doesn't lock the project in a certain environment. We are currenlty on self-hosted GitLab, which is not supported.

Also, wondering what's the reason for not supporting it at this time? Is it technical or business reason? Or just lack of demand for it?

**Comment by Kolahzary** [comment]
any updates?

**Comment by pleroux0** [comment]
This feature would be really helpful for any self-hosted git users.

**Comment by akokskis** [comment]
Are there any updates on getting this feature supported?

It's frustrating that as a user with an external GIT repo (which the organization is not currently interested in moving), I am unable to use yaml pipelines and therefore restricted from using many of the newer features, such as container jobs.

**Comment by AnotherSadGit** [comment]
+1 to support this request.  Not all code is in an Azure Repo or GitHub.

**Comment by cledesma** [comment]
Is this still not supported? We are moving to pure Azure DevOps approach, but at the moment it's a hybrid model, with the Git repository still somewhere on-prem. Why is this not supported via YAML?

**Comment by Bosch-Eli-Black** [comment]
Please vote for this feature suggestion at https://developercommunity.visualstudio.com/t/Using-yaml-build-pipelines-with-external/462453?q=external+git 🙂
