### ISSUE TITLE
azure-pipelines.yml  file errors 

### ISSUE THREAD

**Issue by blvckflame** [microsoft/azure-pipelines-yaml#201]
Hi all , i have two errors while launching new pipeline in azure devops  with JUnit test framework , and java automated gherking tests.

1)/azure-pipelines.yml (Line: 8, Col: 1): A sequence was not expected

2) /azure-pipelines.yml: (Line: 18, Col: 1, Idx: 350) - (Line: 18, Col: 1, Idx: 350): While parsing a block collection, did not find expected '-' indicator.

MY yml file 

# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
- task: PublishTestResults@2
- inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/TEST-*.xml'
- trigger:
- master

- -pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

Please help me , if you know a solution

**Comment by efzwo** [comment]
You should fix your question and at least paste the yaml in a code block.
