### ISSUE TITLE
Pipeline triggered by build completion uses newer source version

### ISSUE THREAD

**Issue by jstoecker** [microsoft/azure-pipelines-yaml#213]
We have two pipelines, A and B, stored as YAML files in our repo. B is triggered by the completion of A. If commit 1 triggers pipeline A, and commit 2 was made before A finishes, then pipeline B uses commit 2 instead of commit 1. In other words, triggered pipelines seem to use the latest version of the branch, not the same version as the triggering build. Is this expected behavior?

I'm thinking I will need to have pipeline A manually queue B using the REST API to achieve what I want. Is there an easier way?

**Comment by JohannesEH** [comment]
I'm not sure if this is expected or not. But you might solve it by publishing artifacts from A which you then download in B.
