### ISSUE TITLE
BitBucket Pull Request Path Filters Timeline?

### ISSUE THREAD

**Issue by BlairMcc** [microsoft/azure-pipelines-yaml#216]
Hey folks,

Is there a timeline for the support of path filters for code coming from BitBucket? It is supported for CI builds so it sounds simple enough? 

Or is it a limitation from what information BitBucket exposes?

`Path filters for PR triggers are not yet supported for Bitbucket Cloud repos.`

Taken from - https://docs.microsoft.com/en-us/azure/devops/pipelines/build/triggers?tabs=yaml&view=azure-devops#pr-triggers

**Comment by ArchSerpo** [comment]
It is no longer there?

I can see it on this cached version

https://webcache.googleusercontent.com/search?q=cache:YruvtsXR5qgJ:https://docs.microsoft.com/bg-bg/azure/devops/pipelines/build/triggers%3Fview%3Dtfs-2018+&cd=2&hl=en&ct=clnk&gl=nz

I will experiment and confirm tomorrow :)

**Comment by ArchSerpo** [comment]
This is now working, paths only declared in the yml file, no manual override in AZDO, and PR builds are kicked off

**Comment by ArchSerpo** [comment]
And it is no longer working... my CI path triggers are all working okay but PR ones have relapsed since I closed this 2 weeks ago

![image](https://user-images.githubusercontent.com/16471369/61408568-6cc8c000-a934-11e9-854d-77136afde446.png)

**Comment by brcrista** [comment]
This appears to be a bug we are investigating.  Tracked here: https://developercommunity.visualstudio.com/content/problem/653939/azure-pipelines-bitbucket-path-triggers-not-workin.html

**Comment by brcrista** [comment]
For the record, this was a bug that has been fixed.
