### ISSUE TITLE
How to pass an optional variable to PowerShell?

### ISSUE THREAD

**Issue by ForrestTrepte** [microsoft/azure-pipelines-yaml#220]
I want to create a build definition that reacts to an optional variable. In other words, I want to be able to queue a build without setting any variables. Just hit Queue in Azure DevOps and go. However, if I *do* go into the Variables section in the Queue dialog then I want my PowerShell script to react to the variable that was set.

Say my variable is called *optionalVar*. If it is set then `$(optionalVar)` will be expanded to the value that I set it to. So far so good. But if *optionalVar* is not set then `$(optionalVar)` won't be expanded, leaving me with exactly the characters `$(optionalVar)` inside my PowerShell script, which will then fail with an error `optionalVar : The term 'optionalVar' is not recognized as the name of a cmdlet, function, script file, or operable program.`

Here are some failed attempts to implement an optional variable:
```
name: $(Year:yyyy).$(DayOfYear).$(BuildId).0

variables:
  pool: Default

trigger: none

jobs:
- job: TestOptionalVariable
  displayName: "Test Optional Variable"
  steps:
  - checkout: self
    clean: false
  - task: PowerShell@2
    displayName: 'PowerShell with Optional Variable'
    inputs:
      targetType: inline
      filePath:
      script: |
        Write-Host "***** BEGIN"

        # FAILURE: This always says NULL even if the YAML variable optionalVar is set.
        if ($optionalVar -eq $null)
        {
          Write-Host "NULL"
        }
        else
        {
          Write-Host "$(optionalVar)"
        }

        # FAILURE: This always says NULL even if the YAML variable optionalVar is set.
        if (Test-Path Variable:\optionalVar)
        {
          Write-Host "$(optionalVar)"
        }
        else
        {
          Write-Host "NULL"
        }

        # FAILURE: Referencing $(optionalVar) inside PowerShell results in an error if the variable is NOT set.
        Write-Host $(optionalVar)

        Write-Host "***** END"
```

I'd like know if there's a good way to implement an optional variable that my users won't need to set if they are happy with default behavior.

**Comment by ForrestTrepte** [comment]
I found a potential solution, but it's ugly. In PowerShell, I can check if the string `'$(optionalVar)'` is literally equal to the text `'$(optionalVar)'`. If so, I treat the variable as unset.

```
name: $(Year:yyyy).$(DayOfYear).$(BuildId).0

variables:
  pool: Default

trigger: none

jobs:
- job: TestOptionalVariable
  displayName: "Test Optional Variable"
  steps:
  - checkout: self
    clean: false
  - task: PowerShell@2
    displayName: 'PowerShell with Optional Variable'
    inputs:
      targetType: inline
      filePath:
      script: |
        Write-Host "***** BEGIN"

        # SUCCESS: This works because it checks the literal value to see if it has been expanded to the 
        # YAML variable's value or hasn't been expanded, leaving it as literally the string '$(optionalVar)'.
        $optionalVarFromYml = '$(optionalVar)'
        $unexpandedLiteralString = '$(optional' + 'Var)'
        if ($optionalVarFromYml -eq $unexpandedLiteralString)
        {
          # Logic goes here for case where optionalVar was not set
          Write-Host "optionalVar was not set"
        }
        else
        {
          # Logic goes here for case where optionalVar was set
          Write-Host "optionalVar was set to $optionalVarFromYml" 
        }

        Write-Host "***** END"
```

Does anyone have a better (less hacky) solution?

**Comment by efzwo** [comment]
Instead of defining the variable in the yaml, you can define it as 'Pipeline Variable' in the UI (Pipeline -> Edit 
 -> three dots -> Variables). Initialize the variable with a default value and check 'Settable at queue time'. This way the variable is always initialized with the default if not changed at queue time. Plus you don't need to remember the full variable name as its directly listed at queue time and can easily be set.

**Comment by ForrestTrepte** [comment]
Thanks, that's also a potential workaround. Unfortunately, though, that kind of variable needs to be defined via the UI rather than in the checked-in build definition yaml. My goal is to create a template that can be used when starting new projects. Put the template in a new repository and--voila!--you immediately have working builds ready to go. That doesn't work so well if I also have to write instructions telling project creators to go into the UI to configure additional settings.

If I could--in the yaml--declare the variable, it's default value, and 'settable at queue time' that would be wonderful!

**Comment by efzwo** [comment]
You can declare the variable with its default value in the yaml and manually override it at queue time. But then have to type the variable name each time you want to override it.

**Comment by ForrestTrepte** [comment]
@efzwo, I couldn't figure out how to do that. According to the [variables documentation](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch#expansion-of-variables), "When you set a variable in the YAML file, do not define it in the web editor as 'settable at queue time'. You cannot currently change variables that are set in the YAML file at queue time. If you need a variable to be settable at queue time, then do not set it in the YAML file." Hence the very ugly workaround described above wherein the variable isn't declared, but the text of an unexpanded value is detected and replaced with the desired default value.

The word *currently* sounds encouraging, though. If the variable declaration in yaml had an option to declare a variable as settable as queue time that would be a great solution to my problem.

**Comment by nkbali** [comment]
Hi, 

This is a very late response but I recently faced a similar scenario and figured a cleaner way to achieve the result was to use a try-catch. In your case the yaml could look as follows:

`name: $(Year:yyyy).$(DayOfYear).$(BuildId).0

variables:
  pool: Default

trigger: none

jobs:
- job: TestOptionalVariable
  displayName: "Test Optional Variable"
  steps:
  - checkout: self
    clean: false
  - task: PowerShell@2
    displayName: 'PowerShell with Optional Variable'
    inputs:
      targetType: inline
      filePath:
      script: |
        Write-Host "***** BEGIN"

        #Try to read the optionalVar. Will succeed if variable exists else run catch block
        try{ 
         $optionalVarFromYml = "$(optionalVar)" 
          Write-Host "optionalVar was set to $optionalVarFromYml"
          #Logic here for variable found
       }
       catch{ 
        Write-Host "optionalVar was not set"
        #Logic here for variable not found
       }
        
        Write-Host "***** END"`

This way you don't have to set the value to a string literal and check for it.
