### ISSUE TITLE
Dynamic YAML Pipeline

### ISSUE THREAD

**Issue by dferretti** [microsoft/azure-pipelines-yaml#222]
Copied from https://github.com/microsoft/azure-pipelines-agent/issues/2271 since this is a better place for it. 

I see you can use templates from remote git repositories with `- template: common.yml@templates` which references an entry from the `repositories` section. Is there a way I can use a similar syntax to define a template location located at an HTTP endpoint?

And this might be dipping too much into feature request territory, but would it be possible to provide parameters to this template HTTP request? I'm envisioning something like an HTTP POST to an HTTP endpoint I control, that receives:

- the git repo location
- the commit sha
- the branch name
- maybe the same set of parameters that exist for the REST endpoint server tasks

And this endpoint is able to use custom logic to generate a dynamic YAML template to return.
Is something like that currently possible or on the roadmap?

This would allow me to analyze the provided repo, for example count the number of C# projects inside it that fit a certain criteria, and return a YAML template that contains a certain number of server or agent tasks to correspond to each project.
I don't know if something like this is possible currently - if I reference a static git repo for templates it has no way of customizing what it provides based on the calling pipeline.

**Comment by dferretti-fig** [comment]
I've been thinking about this some more, and have another idea of how to achieve more dynamic pipelines. Is there any way to have one pipeline step emit additional steps/jobs to the pipeline at runtime? I'm guessing not, based on https://docs.microsoft.com/en-us/azure/devops/pipelines/process/runs?view=azure-devops - it looks like processing the pipeline and expanding the templates is all done up front. 
But it would be neat if my yaml pipeline could just have a single step (maybe a specially named job generator step) which does some local analysis of the source code, and somehow signals back to AzDO to add additional jobs - similar to https://github.com/microsoft/azure-pipelines-tasks/blob/master/docs/authoring/commands.md, maybe something along the lines of `echo ##vso[build.addjob]/some/generated/file.yml`

**Comment by dferretti-fig** [comment]
I've suggested the feature over here: https://developercommunity.visualstudio.com/idea/648401/dynamic-pipeline-generation.html
