### ISSUE TITLE
build cancel with 60 minutes.

### ISSUE THREAD

**Issue by Madushani** [microsoft/azure-pipelines-yaml#227]
Hi given is my azure-pipelines.yml file content. Even though I have set timeoutInMinutes to 120 job fails within 60 minutes. 

trigger:
- master

jobs:
  - job: Package
    timeoutInMinutes: 120

    pool:
     name: 'Hosted Ubuntu 1604'

    steps:
    -  task: Maven@3
      inputs:
        mavenPomFile: 'pom.xml'
        mavenOptions: '-Xmx3072m'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '1.8'
        jdkArchitectureOption: 'x64'
        publishJUnitResults: false
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        goals: 'install'

#[Error 1]
The agent has received a shutdown signal. This can happen when the agent service is stopped, or a manually started agent is canceled. 

##[Error 2]
The job exceeded the maximum allowed time of 01:00:00 and was stopped. Please visit &lt;a href='https://go.microsoft.com/fwlink/?linkid=832649' target='_blank' &gt;parallel jobs&lt;/a&gt; for more information.

**Comment by efzwo** [comment]
Did you read the documentation in the [link](https://docs.microsoft.com/en-us/azure/devops/pipelines/licensing/concurrent-jobs?view=azure-devops#microsoft-hosted-cicd) which is provided with Error 2?

> We provide a **free** tier of service by default in every organization: [...] Private project: One free parallel job that can **run for up to 60 minutes** each time, until you've used 1,800 minutes (30 hours) per month.

**Comment by jonathaneckman** [comment]
I have the same problem. The following job is run on a private agent but stops after 60 mins:

```
jobs:
  - deployment: Service
    timeoutInMinutes: 0
    pool:
      name: 'Private Agent'
```

**Comment by yulev5** [comment]
How did you fix it?

**Comment by xycui** [comment]
I got the issue recently in Release pipeline. The interesting thing is that I have 2 release pipeline very similar. I think it is about the agent pool option update. Previously the VS2017 Host is a separated option under agent pool. But now all the agent option are under **Azure Pipelines** option. 
I think you can try to verify/update **agent specification/pool option under your build/release pipelines edit page.** I solve this problem by updating the option selected under **Azure Pipelines** field.
![image](https://user-images.githubusercontent.com/2989428/70206749-79bf4200-1763-11ea-8ed6-574588da7255.png)
![image](https://user-images.githubusercontent.com/2989428/70206854-cb67cc80-1763-11ea-80d4-355af4eebcfe.png)
