### ISSUE TITLE
No examples of how to use modules

### ISSUE THREAD

**Issue by psblah** [microsoft/azure-pipelines-yaml#236]
i want to know how to pass parameters to a script using scriptArguments.

There's no information, documentation or examples of actually doing this, just the rather vague:

Script Arguments | (Optional) Additional parameters to pass to PowerShell. Can be either ordinal or named parameters.

Please can some examples of the syntax for doing this please be added.

**Comment by Saibamen** [comment]
Moved into Developer Community: https://developercommunity.visualstudio.com/idea/1007463/examples-of-how-to-use-modules.html
Please use "Follow" button on the right to track it
