### ISSUE TITLE
How to use variables properly (delayed expansion?)

### ISSUE THREAD

**Issue by AdamYoblick** [microsoft/azure-pipelines-yaml#24]
Hello,

I'm trying to define a variable to be used in later phases. It seems the way you access variables $(varName) does not work inside of if statements.

Here's what I have:

variables:
  Build.Repository.Clean: true
  _enableTelemetry: true
  _HelixType: build/product

  buildType: public
  ${{ if eq(variables.System.TeamProject, 'internal') }}:
    ${{ if notin(variables.Build.Reason, 'PullRequest') }}:
      ${{ if not(contains(variables.Build.DefinitionName, 'github')) }}:
        buildType: internal

I've trying to branch based on the value of buildType later, but I'm having trouble doing so.

I've tried all of the following:

${{ if eq('$(buildType)', 'public') }}:
${{ if eq($(buildType), 'public') }}:
${{ if eq(variables.buildType, 'public') }}:
${{ if eq('variables.buildType', 'public') }}:
${{ if eq(variables['buildType'], 'public') }}:

But nothing seems to work.

Does this not work in yaml or am I just doing it wrong?

Thanks!
-Adam

**Comment by chcosta** [comment]
https://github.com/Microsoft/azure-pipelines-yaml/pull/3
