### ISSUE TITLE
Variable from expression always converted to string

### ISSUE THREAD

**Issue by arek-avanade** [microsoft/azure-pipelines-yaml#241]
**Problem**
When initializing variable with expression, even if expression returns Bool value, it is always converted to string. Because of that using that variable in conditions later is harder since we need to compare with 'true' or 'false' strings.

**Example**
This is my job-level variable:
`in(variables['Build.Reason'], 'IndividualCI', 'BatchedCI')`
I would expect this variable to be a Bool, however when I run the pipeline it appears to be a string, as indicated in the Prepare job log:
`isCIBuild:
    Parsing expression: <in(variables['Build.Reason'], 'IndividualCI', 'BatchedCI')>
    Evaluating: in(variables['Build.Reason'], 'IndividualCI', 'BatchedCI')
    Expanded: in('Manual', 'IndividualCI', 'BatchedCI')
    Result: 'False'`
(note the result is wrapped in '' which indicates string value)

As a result, when I want to use isCIBuild variable in conditions later, I cannot just write:
`condition: variables.isCIBuild`
because that would always evaluate to `true` (since non-empty string is always converted to true when Bool value is required). 

If I want this to work, I would need to write:
`condition: eq('True', variables.isCIBuild)`

**Comment by Saibamen** [comment]
Moved into Developer Community: https://developercommunity.visualstudio.com/content/problem/1007439/variable-from-expression-always-converted-to-strin.html
Please use "Follow" button on the right to track it

**Comment by Saibamen** [comment]
@arek-avanade: Please go to this link and answer Microsoft team: https://developercommunity.visualstudio.com/content/problem/1007439/variable-from-expression-always-converted-to-strin.html
