### ISSUE TITLE
Combine YAML and classic pipeline concepts?

### ISSUE THREAD

**Issue by drauch** [microsoft/azure-pipelines-yaml#249]
Is it possible to add "classic" pipeline tasks to a YAML pipeline?

We're currently developing a product for which it is important that the WHOLE build pipeline is checked in into the repository and can't be altered. In other words: is it guaranteed that a YAML pipeline is fully checked in into the repository or are there any ways to do additional stuff during the build (configured via the UI, outside of the repository)?

**Comment by Saibamen** [comment]
Moved into Developer Community: https://developercommunity.visualstudio.com/idea/1007461/combine-yaml-and-classic-pipeline-concepts.html
Please use "Follow" button on the right to track it
