### ISSUE TITLE
Any support for else?

### ISSUE THREAD

**Issue by AdamYoblick** [microsoft/azure-pipelines-yaml#25]
Hello,

We have a lot of ${{ if .... }}: in our yaml, and it would be nice to be able to use else as well instead of having to manually write out the inverse of the condition every time.

Any plans for doing this?

Thanks,
-Adam

**Comment by vutkin** [comment]
Why there is no answer so long time?

**Comment by matteotumiati** [comment]
In the arcade repo from dotnet I found this script that seems to be working in an if-else scenario:
https://github.com/dotnet/arcade/blob/master/eng/common/templates/steps/run-script-ifequalelse.yml

**Comment by AdamYoblick** [comment]
This isn’t an else though, it’s two if statements in a row that happen to have inverse conditions.

This is error prone, and the first conditional being true doesn’t prevent the second from being evaluated.

________________________________

**Comment by AdamYoblick** [comment]
(Not very error prone with only one condition but with a complex predicate it can be)

________________________________
