### ISSUE TITLE
Build.SourceVersionMessage in build name not managed

### ISSUE THREAD

**Issue by fhtino** [microsoft/azure-pipelines-yaml#254]
At the beginning of a build pipeline yml file I have:

`name: $(Build.DefinitionName)_$(Build.SourceVersionMessage)_$(Build.SourceVersion)`

When I run it, the build name is created as something like:

`MyName_$(Build.SourceVersionMessage)_5d8a0e057feec126d73f14350e8b1b6e6e570da0`

As you can see, Build.SourceVersionMessage has not been replaced with its value. Is it the expected behavior?

**Comment by igal1c0de4n** [comment]
+1 same issue on my end. Would be nice to see a resolution
