### ISSUE TITLE
Define variable with if/else

### ISSUE THREAD

**Issue by nietras** [microsoft/azure-pipelines-yaml#256]
I would like to define a variable based on evaluating a condition, but simply cannot find a way to do this. It is a pretty simple if/else thing and yet nothing in documentation shows anything like this. :|

```yaml
variables:
  poolName: ${{ if eq(variables['Runner.Run'], 'true') then 'RunnerPool' else 'Default' }}
```
This variable is to be used for defining the pool to run on. Hence, this need to be evaluated before the yaml is actually being run. How can you do this?

```Runner.Run``` is a custom variable defined at queue time.

**Comment by robert-skarzycki** [comment]
I am not sure if it would work for this scenario - evaluate before run - but you can try with "conditional insert". See example: https://github.com/microsoft/azure-pipelines-yaml/issues/278#issuecomment-527765382

**Comment by faelnpaiva** [comment]
I cant open this link https://developercommunity.visualstudio.com/idea/690246/azure-pipelines-yaml-set-variable-based-on-conditi.html   .. it's missing TLS cert ''-.-

**Comment by SimonAlling** [comment]
I have discovered a hack that accomplishes this:

```yaml
- job:
  variables:
    VERBOSE_FLAG: $[
        replace(
          replace(
            eq(lower(variables['System.Debug']), 'true'),
            True,
            '--verbose'
          ),
          False,
          ''
        )
      ]
  steps:
    - task: cURLUploader@2
      inputs:
        # …
        options: --fail --more-curl-flags $(VERBOSE_FLAG)
```

In general, I highly recommend sticking to boolean expressions (for example the application of a boolean-valued [function](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/expressions?view=azure-devops#functions) like `eq`, `gt` or `in`) as the first argument of the inner `replace` application. Had we not done so and instead just written for example

```lang-yaml
        replace(
          replace(
            lower(variables['System.Debug']),
            'true',
            '--verbose'
          ),
          'false',
          ''
        )
```

then, if `System.Debug` were set to e.g. `footruebar`, the value of `VERBOSE_FLAG` would have become `foo--verbosebar`. In contrast, since a boolean-valued function like `eq` always returns either `True` or `False`, we can then safely use `replace` to map those values to whatever we want.

See also [this answer at StackOverflow](https://stackoverflow.com/a/67198023/2135002).

**Comment by asos-tommycouzens** [comment]
This hack is very verbose and not easy to read. I wouldn't want to trouble my developers at having to work out what this does, and would much prefer having something like suggested in the original comment.

**Comment by SimonAlling** [comment]
> This hack is very verbose and not easy to read. I wouldn't want to trouble my developers at having to work out what this does, and would much prefer having something like suggested in the original comment.

I absolutely agree!

Here is a more robust and readable version that the hack above has evolved into:

```
format(replace(replace(
  condition
    , True, '{0}'), False, '{1}'),
  valueIfTrue
    ,
  valueIfFalse
)
```

Of course it still pretty much requires an adjacent comment explaining what's going on, but yeah. It's probably close to the best we can do without proper conditional expression support.

**UPDATE 2025-05-29:** [Azure Pipelines now has built-in support for conditional expressions (`iif`)!](https://learn.microsoft.com/en-us/azure/devops/pipelines/process/expressions?view=azure-devops#iif)

**Comment by Glideh** [comment]
Clever hack but not sure that

```yml
variables:
  poolName: $[
    format(replace(replace(
      eq(variables['Runner.Run'], 'true')
        , True, '{0}'), False, '{1}'),
      'RunnerPool'
        ,
      'Default'
    )
  ]
```

is finally more readable than:

```yml
variables:
  $[ if eq(variables['Runner.Run'], 'true') ]
  poolName: 'RunnerPool'
  $[ else ]
  poolName: 'Default'
```

We'd really need a ternary function here

**Comment by cataggar** [comment]
Thank you @SimonAlling for the workaround! I found it easier to read when I separated out the conditional into its own variable and just used `replace(replace(` without the `format`. My working code was:

``` js
  variables:
    fctSpKeyVaultEmpty: $[eq(variables.fctServicePrincipalKeyVault, '')]
    fctSpKeyVaultProp: $[replace(replace(variables.fctSpKeyVaultEmpty, True, ''), False, 'worker:FCT_SP_KEY_VAULT=$(fctServicePrincipalKeyVault)')]
```

I reopened https://developercommunity.visualstudio.com/t/Support-ternaryiif-syntax-in-expression/643294 . Please upvote it. If that suggestion was accepted, the resulting code would look something like:

``` js
  variables:
    fctSpKeyVaultEmpty: $[eq(variables.fctServicePrincipalKeyVault, '')]
    fctSpKeyVaultProp: $[iif(variables.fctSpKeyVaultEmpty, '', 'worker:FCT_SP_KEY_VAULT=$(fctServicePrincipalKeyVault)')]
```

**Comment by ohads-MSFT** [comment]
> Clever hack but not sure that
> 
> ```yaml
> variables:
>   poolName: $[
>     format(replace(replace(
>       eq(variables['Runner.Run'], 'true')
>         , True, '{0}'), False, '{1}'),
>       'RunnerPool'
>         ,
>       'Default'
>     )
>   ]
> ```
> 
> is finally more readable than:
> 
> ```yaml
> variables:
>   $[ if eq(variables['Runner.Run'], 'true') ]:
>     poolName: 'RunnerPool'
>   $[ else ]:
>     poolName: 'Default'
> ```
> 
> We'd really need a ternary function here

This won't work, conditionals only work when using template syntax (`${{ ... }}`): https://learn.microsoft.com/en-us/azure/devops/pipelines/process/expressions?view=azure-devops#conditional-insertion
