### ISSUE TITLE
how to refer environment specific variable group in azure-pipelines.yaml

### ISSUE THREAD

**Issue by get2arun** [microsoft/azure-pipelines-yaml#263]
We have separate branches for each environment (dev, staging, production). In the dev branch azure-pipelines.yaml, have variable group as "dev-env-group-name" and when pull request is made to merge the code to staging branch, azure-pipelines.yaml is updated with "dev-env-group-name" but I want to have "staging-env-group-name". 
How can I configure and use the specific variable group for my environments ? 
I can pass the group variable dynamically at build time? I think it should be handled differently because the variable groups specific to environments are not changed and I believe it should not be passed at build time as an argument, rather it should be handled differently.
Is there any better way to handle this efficiently?

**Comment by worldspawn** [comment]
No. The masses are currently clamouring for the ability for a group name to be dynamic. Eg: `group: my-vars-$(env)` But that is not supported. I have not been able to find a pleasant solution, I currently this crap in my yaml:

```
  - ${{ if eq(variables['Build.SourceBranchName'], 'dev') }}:
      - group: drawboardteams_dev_dev
  - ${{ if eq(variables['Build.SourceBranchName'], 'test') }}:
      - group: drawboardteams_dev_test
  - ${{ if eq(variables['Build.SourceBranchName'], 'preprod') }}:
      - group: drawboardteams_dev_preprod
  - ${{ if eq(variables['Build.SourceBranchName'], 'master') }}:
      - group: drawboardteams_prod_prod
```

...which is probably still better than updating ur yaml all the time.
