### ISSUE TITLE
replace expression

### ISSUE THREAD

**Issue by cmeyertons** [microsoft/azure-pipelines-yaml#276]
would be fantastic if there was a replace expression to do regex replacement on variables at onset!

i.e.

```yaml
variables:
  branchName: ${{replace(variables['System.PullRequest.SourceBranch'], '/', '_')}}
```

**Comment by wildmichael** [comment]
I second this request. My use-case would also be to mangle the `build.SourceBranch` variable when creating the build number. I would like to remove the `refs/heads/` prefix for branches and the `refs/` prefix for pull requests. They add nothing of value and are just noise in this context.

Alternatively, just give me a `SourceBranch`-derived variable that does this, but not like `SourceBranchName` which drops the `feature/`, `release/` and `hotfix/` prefixes when using the git-flow branching model.

**Comment by escalonn** [comment]
> Alternatively, just give me a `SourceBranch`-derived variable that does this, but not like `SourceBranchName` which drops the `feature/`, `release/` and `hotfix/` prefixes when using the git-flow branching model.

A million times this.

**Comment by cmeyertons** [comment]
Yes - I created this issue after realizing there was absolutely zero way to get a consistent branch variable...

**Comment by KiLLeRRaT** [comment]
I found something that helps quite a lot: https://docs.microsoft.com/en-us/azure/devops/pipelines/process/expressions?view=azure-devops#qa

I added this step:

```
- bash: |
    v=$(echo $(GitVersion.InformationalVersion))
    v=${v//[\/_]/-} # replace all /' and _'s in the version string with -'s
    echo "This is the escaped version: $v2"
       
    # create pipeline variable
    echo "##vso[task.setvariable variable=GitVersion.InformationalVersionEscaped]$v"
```

Note that I also added `GitVersion.InformationalVersionEscaped` into my variables at the top.  Not sure if you need this or not.

**Comment by lukeapage** [comment]
I had the problem where I wanted to use the result of a replace expression in a expression - to get round it I had to define a job which used powershell to do the replacement and then variables setup in the next job that used the result of the replace...

**Comment by anatolybolshakov** [comment]
Hi @lukeapage could you please create a ticket on https://developercommunity.visualstudio.com/search?space=21 to get right eyes on your question? This repo is mostly for yaml project templates, so this would be a better place to get a quick support...
