### ISSUE TITLE
Introduce a hashstring(...), uniquestring() and safestring(...) functions

### ISSUE THREAD

**Issue by mitchdenny** [microsoft/azure-pipelines-yaml#281]
I'd like to propose that Azure Pipelines introduce three new functions that can be used within templates, they would be:

```hashstring(...)```, ```uniquestring()``` and ```safestring(...)```

Here is why each would be useful:

- ```hashstring(...)```: Given a set of string values, compute a hash which is unique based on the input values. I'd imagine this being a cryptographic hash value.
- ```uniquestring()```: Output a unique string - this would typically be placed into a parameter value so it could be reused across the template. It would be unique to each run.
- ```safestring(...)```: Similar in intent to ```hashstring(...)``` but the output is designed to take something that is not safe for use as say a job or stage name and replace invalid characters so that it is. However it differs from ```hashstring(...)``` in that the output is predictable whilst authoring templates so you can reference the string in other stages.

Here is how I would use ```safestring(...)``` as an example. I have a template that uses ```${{each ...}}``` to emit stages based on the items in a YAML array. However I want a stage that is dependent on all those stages. Unfortunately the items in the list are not safe strings in terms of job and stage names and so I need a function that I can use to translate the item into the list to a job name. I would then use another ```${{each ...}}``` to emit the ```dependsOn``` attribute on the follow on stage.

**Comment by mitchdenny** [comment]
@vtbassmatt what are your thoughts on this? If this is something that you are interested in I would be happy to work on the implementation.

**Comment by vtbassmatt** [comment]
I'm not opposed. As you're doubtless aware, you'd have to land that in the Azure Pipelines service codebase. A good start would be a design doc we can bash on first. While I want to work in the open as much as we can, I think for this, we'd start with a doc in a private repo (since it covers closed-source product code).

**Comment by mitchdenny** [comment]
OK - sounds like a plan. I'll get something to you.

**Comment by dperez83** [comment]
Are these 3 functions (hashstring, uniquestring and safestring) live and working in Azure pipelines yml? I cannot use safestring it gives me an error. I need this to make the project name suitable to a deployment name.

**Comment by mitchdenny** [comment]
I don't think it ended up being implemented.

**Comment by dperez83** [comment]
I ended using the _replace_ function to get rid of the not supported chars, but a _safestring_ would be 1000 times better.

Can you open a new issue so it stays on the radar? Those 3 function would be absolutely useful when using fully the pipelines specially when the names must not repeat.

A _guid_ function would be also nice when we need to generate a unique name.

Thank you!

**Comment by dperez83** [comment]
> I don't think it ended up being implemented.

Can you open a new issue so it stays on the radar? Those 3 functions are absolutely useful when we need to create a unique name (that is required in the pipelines). I ended up using the _replace_ function to get rid of the forbidden chars but the _safestring_ is absolutely what I need and 1000 times better and future proof.

I would also add a _guid_ function so it will be easy to create a unique name any time.

Thank you!
