### ISSUE TITLE
Job reported as succeeded when it actually failed

### ISSUE THREAD

**Issue by MisinformedDNA** [microsoft/azure-pipelines-yaml#283]
A couple of issues I noticed from my first "successful" multi-stage pipeline:

![image](https://user-images.githubusercontent.com/1784452/62412965-119efa80-b5cf-11e9-9124-1b04f385b42c.png)

1. It says that the job ran longer than 60 minutes, but it actually ran 6 seconds shorter, so no error is expected.
2. Even if we were to accept the error as valid, the left outline still shows the job as successful.
3. Even though the outline shows all successes, the pipeline as a whole still shows as a failure.

Note: I have not actually enabled the multi-stage preview, but everything else seems to work fine and I can try testing with that enabled as well.

**Comment by Saibamen** [comment]
Moved into Developer Community: https://developercommunity.visualstudio.com/content/problem/1007436/job-reported-as-succeeded-when-it-actually-failed.html
Please use "Follow" button on the right to track it

**Comment by Saibamen** [comment]
@MisinformedDNA: Sam Jiang added new comment, please go to https://developercommunity.visualstudio.com/content/problem/1007436/job-reported-as-succeeded-when-it-actually-failed.html and write to him if this bug is still here or not
