### ISSUE TITLE
Allow Containers to be used for Deployment Jobs

### ISSUE THREAD

**Issue by jdkemme** [microsoft/azure-pipelines-yaml#288]
Please allow containers to be used for deployment jobs, just like regular jobs.  We depend on containers for many required tools depending on the build/release and are unable to use deployment jobs without deploying new monolithic agents with all tools installed to handle deployment jobs

  jobs:
    - deployment: publish
      pool: Container
      container: python:3.7-slim 

Unexpected property container

**Comment by mathieu-benoit** [comment]
+ 1, would be great indeed!

**Comment by RoopeshNair** [comment]
yes, we do have plans to support it. However, it will be a while before we can get to it.

**Comment by mathieu-benoit** [comment]
I haven't tried yet but it looks like it's taken into account on 2020-01-13 release: https://docs.microsoft.com/en-us/azure/devops/release-notes/2020/sprint-163-update#use-pipeline-decorators-to-inject-steps-automatically-in-a-deployment-job

**Comment by RoopeshNair** [comment]
Yes, we recently added support for running deployment jobs in a container. Here is the [schema for deployment job](https://docs.microsoft.com/en-in/azure/devops/pipelines/process/deployment-jobs?view=azure-devops#schema)
