### ISSUE TITLE
Prevent CI pipeline when PR build is triggered

### ISSUE THREAD

**Issue by scabana** [microsoft/azure-pipelines-yaml#296]
Hi, 

We have a setup where all branches of a repo triggers a CI build. When a PR is opened with a build policy, 2 builds gets triggered (1 for the PR and 1 for the CI). It would be nice to be able to prevent the CI build for a branch that has a pending active PR.

**Comment by Saibamen** [comment]
Moved into Developer Community: https://developercommunity.visualstudio.com/idea/1007435/prevent-ci-pipeline-when-pr-build-is-triggered.html
