### ISSUE TITLE
One pipeline to rule them all?

### ISSUE THREAD

**Issue by MisinformedDNA** [microsoft/azure-pipelines-yaml#305]
Should we prefer one pipeline or various pipelines?

For instance, the sample documentation shows "Build" and "Deploy" as separate stages and not as separate pipelines.

Having it all in one pipeline makes it easier to understand the flow, but having to run "Build" every time, even if I only want to test "Deploy", is highly frustrating.

**Comment by SQLHorizons** [comment]
@MisinformedDNA , came across this [Triggers in pipelines](https://github.com/microsoft/azure-pipelines-yaml/blob/master/design/pipeline-triggers.md).  Not had chance to read through or try it out but it could be what we're both looking for?

**Comment by MisinformedDNA** [comment]
Yeah, I don't think so. I'm already using triggers, but don't see how they would further help me.
