### ISSUE TITLE
Templates in other repositories may not specify a repository source when referencing another template.

### ISSUE THREAD

**Issue by mattleibow** [microsoft/azure-pipelines-yaml#309]
I am busy creating some templates that will work across several public repositories. As a result, I have some shared steps that must run, but also include some internal/proprietary steps. I used to have duplicated yaml, and each will pull in the internal template. This was fine, but I am hoping to remove all the duplicate yaml.

Because we also want to use templates that are in private repos, we could just include it in the main yaml. However, the internal template is a single step that signs packages with private keys and behind a VPN. But, the entire set of steps do a bit more, and duplicating that is not so great, and we can't bring the private step out.

Is this something that you would be interested in supporting?

I don't see an issue with having to manually list all the repositories in the main template to prevent any malicious activity - since we can control the main template.

**Comment by mattleibow** [comment]
For now, I am going to try and see if I can clone/download that template on the agent and use it there.

**Comment by mattleibow** [comment]
As a workaround, I moved the entire job template into the internal repository. Not the most ideal since it is fairly specific.

**Comment by DerGary** [comment]
We do have the same Problem. Why is this "not allowed"?

**Comment by shavij** [comment]
Running into the same issue and blocking progress. Would be great to support this. In the meantime, is there a workaround? Here is my scenario. Have also specified the repositories resources.

Repo1 - Current repo
Repo2 - Repo where the build template resides

jobs:
- template: general_build_template.yml@Repo2
  parameters:
    buildSteps:
    - template: build_steps.yml@Repo1

**Comment by NateB2** [comment]
Same problem here.  We'd love to move to YAML deploy/release pipelines, but this is a blocking issue for us.

**Comment by manivasm** [comment]
this has been added as new feature 

https://developercommunity.visualstudio.com/idea/820065/templates-in-other-repositories-may-not-specify-a.html

upvote this.
