### ISSUE TITLE
Environment doesn't list Rejected Checks?

### ISSUE THREAD

**Issue by mathieu-benoit** [microsoft/azure-pipelines-yaml#315]
It appears that an [Environment](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema#environment) will just list Jobs/Phases in Success or Failed state but not Rejected when using [Checks](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/checks?view=azure-DevOps).
I think it would be ideal to list Rejected as well, thoughts?

**Comment by shashban** [comment]
That is correct. 
The intent of listing jobs in environments is to provide a view of what got deployed to the environment. If an approval/ check was rejected, the state of the environment did not change. 
Could you elaborate on the scenario you are trying to achieve by having failed checks/ skipped jobs visible on the environment?

**Comment by mathieu-benoit** [comment]
While learning about this concept of Environment]() the "Deployment History" intent described about this feature seemed really interesting. But again it's just listing the Failed/Success run. Having the Rejected will help customer to leverage this "single place of history" per Environment. Does that make sense?
