### ISSUE TITLE
Configure retention policy

### ISSUE THREAD

**Issue by giggio** [microsoft/azure-pipelines-yaml#316]
Right now it seems we cannot configure retention policies with yaml builds. We need to do that.

This was mentioned on [spring 142, almost an year ago](https://docs.microsoft.com/en-us/azure/devops/release-notes/2018/sprint-142-update#default-retention-for-yaml-pipelines).

Is there a way to retain yaml builds for longer than 30 days? I need at least the last build to be retained, and the last successful one as well, if it is not the last build.

**Comment by Kollibri** [comment]
I need this too.

**Comment by SebHonorine** [comment]
Yes it is an issue for us too and the information seems to be not running arround this case. 30 days is not enough. Any information ?

**Comment by aholler2** [comment]
We need this.

**Comment by nimor109** [comment]
We need this too. We can't move to Yaml without it

**Comment by biyimaks** [comment]
While this isn't an official fix, you can work around the issue by adding a task to call a REST API (https://docs.microsoft.com/en-us/rest/api/azure/devops/build/leases/add?view=azure-devops-rest-6.0) to retain the build for as long as you need. Setting the `daysValid` member in the REST call along with setting a condition on the stage like `condition: and(succeeded(), eq(variables['IsPROD'], 'true'))` should do the trick

**Comment by DerGary** [comment]
We would also like this feature because we publish symbols to the build and they get deleted when the build gets deleted. But the NuGet Package that was created may live a much longer live.
