### ISSUE TITLE
Condition evaluation in Multi-stage YAML

### ISSUE THREAD

**Issue by TroySchmidt** [microsoft/azure-pipelines-yaml#318]
If the first stage in a multistage pipeline has a condition that evaluates to false, the second stage will skip as well by default.  You must include `condition: always()` on the second stage to force it to run when the first stage is skipped for a condition evaluation.

**Comment by CyborgWombat** [comment]
This times a hundred. I've got a huge deployment pipeline that has jobs that should wait for the success of some dependent jobs but i would like them to run if the previous stage has been skipped. Now i need to add the `condition: always()` so they will get triggered.

**Comment by escalonn** [comment]
Only one behavior here can be default, unless they add some sort of global config. Is `always()` really a more reasonable default than `succeeded()`? Maybe it is, but it's not obvious.

**Comment by CyborgWombat** [comment]
In my case:

`Stage B` is dependent on `Stage A`
If `Stage A` succeeds, `Stage B` is triggered
If `Stage A` fails, `Stage B` is not triggered
If `Stage A` is skipped, `Stage B` is not triggered. If I want it to be, i need to add `always()` to the conditions, then it will wait for `Stage A` but will run regardless of `Stage A`'s outcome.

**Comment by matteotumiati** [comment]
> Only one behavior here can be default, unless they add some sort of global config. Is `always()` really a more reasonable default than `succeeded()`? Maybe it is, but it's not obvious.

Totally agree on that. I honestly would like to keep `succeeded()` as default, just because I don't want to handle conditions on every stage (or every job, and I have so many) that gets executed after the one that can be skipped. 

What I really need in this scenario is either:
1. A new `skipped()` state that I can check with a custom condition on a later stage/job
1. A way to set the stage as `succeeded()` if skipped (using global config, a stage/job level decision or both)

**Comment by Saibamen** [comment]
Moved into Developer Community: https://developercommunity.visualstudio.com/content/problem/1007468/condition-evaluation-in-multi-stage-yaml.html
Please use "Follow" button on the right to track it

**Comment by Saibamen** [comment]
@TroySchmidt: Please go to this link and answer Microsoft team: https://developercommunity.visualstudio.com/content/problem/1007468/condition-evaluation-in-multi-stage-yaml.html
