### ISSUE TITLE
Running jobs locally

### ISSUE THREAD

**Issue by TingluoHuang** [microsoft/azure-pipelines-yaml#32]
copy from: https://github.com/Microsoft/azure-pipelines-agent/issues/1887

Have you tried trouble shooting?
N/A

Agent Version and Platform
Agent version: 2.140.2

OS of the machine running the agent? OSX/Windows/Linux/...
Windows

VSTS Type and Version
VisualStudio.com

If VisualStudio.com, what is your account name?
http://uipath.visualstudio.com

What's not working?
As per this issue, we know that some time ago the agent supported running jobs locally (it was some kind of a hidden feature, but this prospect excited us). What's the status on this? Is there any way of running builds locally? This would really help for speeding up testing!

Thank you!

**Comment by alexiffland** [comment]
Any news on this? What is the current state of development regarding running jobs locally?

**Comment by Skintkingle** [comment]
This would be a great feature to have as we are moving more and more to Yaml build definitions in our projects, to have our development build process directly mimic our CI builds would be perfect

**Comment by ardalis** [comment]
Latest word on this?

**Comment by tomgs** [comment]
Wrote an [SO question](https://stackoverflow.com/questions/56464851/how-can-i-mock-a-ci-agent-server?noredirect=1#comment100152138_56464851) that lead me here. Would be great to see this being implemented somehow.

**Comment by tomgs** [comment]
Has any update been made on this, possibly?

**Comment by Saibamen** [comment]
Moved into Developer Community: https://developercommunity.visualstudio.com/idea/1007480/running-jobs-locally.html
Please use "Follow" button on the right to track it
