### ISSUE TITLE
How to set "Tag source: 'on success'" in YAML

### ISSUE THREAD

**Issue by lanluu** [microsoft/azure-pipelines-yaml#325]
Hi,

I could not find any template/doc about the configuration for **"checkout" -> "Tag source: 'on success'"** in **YAML**. Is it possible?

![image](https://user-images.githubusercontent.com/3998945/64519962-73046880-d2f5-11e9-8302-7de8781ee7e7.png)

Thank you for your feedbacks!
BR
Lan

**Comment by FizzBuzz791** [comment]
This is a duplicate of #139

**Comment by konstantinmiller** [comment]
Could you please provide a link to this topic in the Developer Community? I couldn't find it.

**Comment by wwestrop** [comment]
@konstantinmiller [It is here](https://developercommunity.visualstudio.com/idea/1007477/missing-gui-option-create-git-tag-after-successful.html)
