### ISSUE TITLE
Coalesce expression doesn't appear to be skipping empty string inputs

### ISSUE THREAD

**Issue by PureWeen** [microsoft/azure-pipelines-yaml#342]
The following YAML expression

https://github.com/xamarin/Xamarin.Forms/blob/4f24701c64b63f7616493f197c6cc57cbdcdc068/build/steps/build-windows.yml#L41

```
"Install .net core COALESCE: ${{ coalesce(parameters.DOTNET_VERSION_GLOBAL, parameters.DOTNET_VERSION_PARAM) }} PARAM: '${{ parameters.DOTNET_VERSION_PARAM }}' GLOBAL: '${{ parameters.DOTNET_VERSION_GLOBAL }}' "
```

Yields the following string when my build runs
```
Install .net core COALESCE: PARAM: '2.1.801' GLOBAL: ''
```

According to the documentation of coalesce
```
coalesce
Evaluates the parameters in order, and returns the value that does not equal null or empty-string.
```

So it seems like the coalesce expression should be returning *parameters.DOTNET_VERSION_PARAM* since that's not an empty string where as *parameters.DOTNET_VERSION_GLOBAL* is

**Comment by jgn-epp** [comment]
I'm having a very similar issue. Its pretty frustrating that it doesn't appear to be working as described in the docs.
