### ISSUE TITLE
Mark pipeline status 'Completed' with optional stages

### ISSUE THREAD

**Issue by sadedil** [microsoft/azure-pipelines-yaml#344]
I have 3 steps YAML pipeline **Build**, **Deploy To Development** and **Deploy to Test**.

**My needs are very basic:**
- a. When some code changes in `master`, pipelines triggers (*OK*)
- b. With this changes, **Build** and **Deploy To Development** stages automatically runs (*OK*)
- c. **Deploy to Test** stages waits until I approve (*OK*)

But I've facing a problem if I don't approve the **Stage - c**, the pipeline never ends and always shows an in-progress icon. So whenever I check the Pipelines page, I saw all pipelines are running but actually is not.

Worse part is the whole pipeline falls in *Failed* status after two weeks.

**My question is**, is there any way to mark **Deploy to Test** stage as optional? The pipeline should be completed without this stage but optionally I want to able to execute this step manually.

---

![image](https://user-images.githubusercontent.com/2132971/65936886-bbabcf00-e426-11e9-93f7-19b646b823c8.png)

**Comment by guibirow** [comment]
You can review and mask as rejected if you don't want to deploy. The only problem is it masks the build as failed.
Other option is Mark as  approved and then cancel before it starts

It should have the cancel option always available tough

**Comment by sadedil** [comment]
Yes these are some options but it still looks failed and it's decreasing the average of successful build. Also these steps are all manual and I don't want to do this steps manually.

**Comment by Barsonax** [comment]
> You can review and mask as rejected if you don't want to deploy.

That means reviewing every build. Not every build will get a review as that is too much hassle. It shouldn't report waiting forever if the review never comes (or atleast make a option for this).

Consider my situation where every build could be deployed if I wanted to. The approval is not mandatory but a optional one, only needed if you want to deploy something.

**Comment by guibirow** [comment]
I've noticed yesterday, now you can cancel the pipeline when it is waiting for review and it won't mark as failed anymore.

If you don't review the build in a few days(I think is 2d) they get cancelled automatically, you don't need to review them all.

**Comment by sadedil** [comment]
Hi @guibirow;

I've tried what you've said five minutes ago and still the same.

![image](https://user-images.githubusercontent.com/2132971/67548720-348f0580-f70b-11e9-84d0-7192e08d38c3.png)

**Comment by guibirow** [comment]
I've noticed only yesterday, if this is a new release, might take a few weeks to deploy to all accounts, they have released a new sprint last week, but there are no mention to this.

**Comment by ctyar** [comment]
If you cancel an optional stage build status will be yellow which seems like something is wrong

![Screenshot_2019-11-05 ctyar pingct](https://user-images.githubusercontent.com/1432648/68191348-a6493800-ffc4-11e9-931c-1a239c30a680.png)

**Comment by 4nandP** [comment]
We need something like this, it's hard to advocate for yaml pipelines when features like source tagging and optional deployments aren't first class features.

**Comment by helmerm** [comment]
Is there any update on this one?

**Comment by Barsonax** [comment]
This issue is not fixed and now just getting closed by a bot?

**Comment by Saibamen** [comment]
@Barsonax: Closed by bot... I am moving some issues from here to Developer Community by hand...
Microsoft should move it by some script or something...

Moved into Developer Community: https://developercommunity.visualstudio.com/content/problem/1007470/mark-pipeline-status-completed-with-optional-stage-1.html
Please use "Follow" button on the right to track it

**Comment by Saibamen** [comment]
Hello, I have answer from Microsoft support team:

Hi,

Thanks for posting in Developer Community.

According to your description, it looks like you want to skip stages in a YAML pipeline.

![image](https://user-images.githubusercontent.com/905878/80353056-14383300-8875-11ea-8d14-e5c9ad7e0ce7.png)

Please check if this issue still persists.

If there is any misunderstanding, please share your sample yaml file and screenshots to help me understand the problem.

Look forward to hearing from you.

**Comment by sadedil** [comment]
Hi @Saibamen,

We use push or pr triggers to start pipelines so we are not able to choose (or not able to know at this time) which stage should run.

For example
- Pipelines in the red box, runs until preprod and we didn't want to go further (preprod and prod)
- The pipeline in the green box, we have approved to run all steps. So all stages processed and this run completed successfully.

**The problem is**: After 14 days, red ones gets canceled one by one because of the timeout and this causes some side effects. Such decreasing the pipeline success rate, getting an annoying mail to with "pipeline failed" title, etc.

![image](https://user-images.githubusercontent.com/2132971/80353706-66318680-887e-11ea-8b3b-bb0f39c68fb5.png)

**Comment by Saibamen** [comment]
I posted your answer in DC

**Comment by helmerm** [comment]
There is already a smiliar issue here, please vote

https://developercommunity.visualstudio.com/content/idea/785741/mark-pipeline-status-completed-with-optional-stage.html
