### ISSUE TITLE
stage condition using parameter in contains expression

### ISSUE THREAD

**Issue by artemijspavlovs** [microsoft/azure-pipelines-yaml#347]
I want to enable the ability to skip some of the stages while using YAML pipelines. To do this, I created a pipeline variable called environments and am trying to use a condition parameter inside a template that looks like follows.

azure-pipeline.yml

```
- template: ../../templates/template.yml
  parameters:
    envName : dev
- template: ../../templates/template.yml
  parameters:
    envName : prod

```

template.yml

```
parameters:
  envName: ''
stages:
- stage: Stage Name
  condition: and(succeeded(), contains(variables.environments, ${{ parameters.envName }} ))
```

where **variables.environments** is a pipeline variable with a list of stages that I want to run.

**Expected behavior:**

**${{ parameters.envName }}** is evaluated as a string and condition is executed successfully that results into skipping stages that are not defined in **variables.environments** pipeline variable

**Actual behavior:**

Azure DevOps returns an error message during variable definition

```
An error occurred while loading the YAML build pipeline. Unrecognized value: 'dev'. Located at position 64 within expression: and(succeeded(), containsValue(variables.environments, dev )). For more help, refer to https://go.microsoft.com/fwlink/?linkid=842996
```

**Testing Scenarios:**

```
and(succeeded(), contains(variables.release_environments, 'dev' ))
```

this works just fine because it's a static string and there's no problem with type evaluation. the condition works in this case.

```
and(succeeded(), contains(variables.release_environments, '${{ parameters.envName }}' ))
```

this makes the pipeline run but the condition does not work, I'm assuming it's because the **${{ parameters.envName }}** is transformed into a string and the value of parameter is not retrieved.

I also tried to set condition as a parameter on template level and provide it like 
```
- template: ../../templates/deploy-stage.yml
  parameters:
    envName : dev
    condition: and(succeeded(), contains(variables.release_environments, 'dev' ))
```

this also results into pipeline running but condition not working.

`containsValue` behaves in the same manner

**Comment by BlairMcc** [comment]
I am having a similar issue here, contains just doesn't want to work for me. I am tempted to ditch my CSV string and set a flag for each check...

`condition: eq(variables.buildCore, true)`

https://github.com/MicrosoftDocs/vsts-docs/issues/6001

**Comment by esahanhunter** [comment]
it works ! 
i see that you are trying to evaluate here 
and(succeeded(), contains(variables.release_environments, '${{ parameters.envName }}' ))

instead  
and(succeeded(), contains(variables.release_environments, variables.envName ))
Note i have used variable here

**Comment by jnancel** [comment]
Hello guys,

For the record, I believe the error is due to the fact that you're missing `'` around your values.

It should work with 
```
parameters:
  envName: ''
stages:
- stage: Stage Name
  condition: and(succeeded(), contains(variables.environments, ${{ parameters.envName }} ))
  ```

What I deduced from the tests I made is that `${{ parameters.envName }}` is replaced at build time by the proper value, and if you don't add single quotes around your value, Azure DevOps tries to evaluate the value not as a string but as an Azure Pipelines element, which logically fails.
