### ISSUE TITLE
Improve integration with GitHub checks for multi-stage pipelines

### ISSUE THREAD

**Issue by henryju** [microsoft/azure-pipelines-yaml#359]
Hi,

I have written a complex multi-stage pipeline to build a project hosted on GitHub. Each stage is made of multiple jobs (some of them are matrix), and the result in GitHub PR UI is not nice IMO.
What about only reporting stage status when pipeline contains more than one stage? Also maybe try to find a better name for each check.

![image](https://user-images.githubusercontent.com/281596/66998629-dd6aae80-f0d4-11e9-878f-d374e64d38bd.png)

![image](https://user-images.githubusercontent.com/281596/66998363-67664780-f0d4-11e9-8ef8-cdc6d053bc2b.png)

For reference this is how my pipeline look like in Azure:
![image](https://user-images.githubusercontent.com/281596/66998787-23277700-f0d5-11e9-8828-41fef0bfb375.png)

**Comment by tomkerkhove** [comment]
Personally I think this is better than it was before, but that's just my opinion.

**Comment by amaslenn** [comment]
Are there any updates on this topic? I'd prefer a combined status for the whole Stage for Github check status too.

I need to run many jobs in parallel and that is only possible with stages/jobs. And since each job is a separate check it pollutes Github status page quite a lot.
