### ISSUE TITLE
To use variables in service connection inputs, we need to use expressions. Just using plain variables doesn't work

### ISSUE THREAD

**Issue by tejasd1990** [microsoft/azure-pipelines-yaml#363]
To use variables in service connection inputs, we need to use expressions like _ConnectedServiceName: ${{ variables.ConnectedServiceName_1 }}_. Just using plain variables like _$( variables.ConnectedServiceName_1)_ doesn't work. It works for other inputs though.
Is this behaviour documented somewhere?
Based on this issue https://github.com/microsoft/azure-pipelines-tasks/issues/11555

**Comment by runemoennike** [comment]
In fact the exact opposite is documented:

"Service connection cannot be specified by variable" from https://docs.microsoft.com/en-us/azure/devops/pipelines/library/service-endpoints?view=azure-devops&tabs=yaml

I wasted a full day on this, and almost gave up thinking it wasn't possible. @shashban @prativen  @Lovakumar @kasubram can one of you reassign this to the documentation team so people can at least have a chance of finding the solution to this inconsistency without wasting so much time?
