### ISSUE TITLE
User-defined variables not evaluated at plan compilation time

### ISSUE THREAD

**Issue by timmkrause** [microsoft/azure-pipelines-yaml#372]
I have a user-defined variable

![image](https://user-images.githubusercontent.com/2163179/67859603-58dc4f00-fb1c-11e9-8801-16c0e5db56b7.png)

which is **not** mentioned in the `variables:` section.

I would like to use this variable for a conditional insert on the stage level:

```
# ...
- ${{ if eq(variables.DestroyEnvironment, 'true') }}:
  - template: stages/destroy.yml
    parameters:
      # ...
```

Unfortunately the stage never shows up.
If I add the variable to the variables section it works:

```
variables:
  DestroyEnvironment: 'true'
```

So it's basically working, but user-defined variables "from outside" are not taken into account for the plan compilation.

**Comment by denravonska** [comment]
I'm having the same issue. Our users can queue builds manually and provide a `$(buildType)` to tell the pipe what type of build to do. If the type is `development` the pipe needs to do additional steps. I could use conditions if that worked for templates but it doesn't (#30), so I need to use conditional insert.

**Comment by vtbassmatt** [comment]
Variables from the pipeline definition (in the web UI) are not available to the template parser. See https://github.com/microsoft/azure-pipelines-yaml/blob/master/design/runtime-parameters.md for how we're solving this. That feature is under active development and I hope to see it ship in February 2020.

**Comment by denravonska** [comment]
The UI hints alone will be worth the wait.
