### ISSUE TITLE
Configure Pipeline Step is Skipped

### ISSUE THREAD

**Issue by cawoodm** [microsoft/azure-pipelines-yaml#378]
It was, until a few days ago, possible to create azure devops pipelines based on existing .yml files in our repository. This seems to have been lost for some repositories.

For "some" repos, after you choose "Where is your code?" and "Azure Repos Git" you are taken to a Repo selection screen and then a new "azure-pipelines.yml" file. The step "Configure your pipeline" with "Select an existing YAML file" is just missing.

![image](https://user-images.githubusercontent.com/498834/68050125-ca66f980-fce4-11e9-9225-06d5d4dc268e.png)

![image](https://user-images.githubusercontent.com/498834/68050075-b3280c00-fce4-11e9-8dbf-0f01b940d500.png)

**Comment by nickydraz** [comment]
Not a fix for setting up via that exact workflow, but I found that you could still use an existing yaml file if you created the build by doing:
- Navigate to branches screen
- Select a branch
- Select the "Set up build" button
<img width="516" alt="image" src="https://user-images.githubusercontent.com/10491055/76221874-c04f8d00-61e7-11ea-9768-3c14c634496a.png">

- From there you should be taken directly to the Configure screen, where you can choose an existing yaml file to start with

<img width="749" alt="image" src="https://user-images.githubusercontent.com/10491055/76221947-d8bfa780-61e7-11ea-8389-a6dbfe31e07f.png">

**Comment by adityavikasd** [comment]
I ran into the same issue. This is because my repository had a `azure-pipelines.yml` file at the root level. Deleting it or renaming it fixed the issue

**Comment by ZaahierAdams** [comment]
> I ran into the same issue. This is because my repository had a `azure-pipelines.yml` file at the root level. Deleting it or renaming it fixed the issue

This worked. Thanks

**Comment by derekwilliamsliquidx** [comment]
Deleting or renaming pipeline files should never be required. I am encountering this issue.

I don't know what changed, but this is a serious regression.

**Comment by CloudFulness** [comment]
You need to setup the default (azure-pipelines.yml) pipeline first. Once that pipeline exists the configure step won't be skipped anymore when adding more pipelines based on the same repo.
