### ISSUE TITLE
Add pull request trigger to yaml

### ISSUE THREAD

**Issue by mikeharder** [Microsoft/azure-pipelines-yaml#38]
Please add pull request triggers to yaml (currently [not supported](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/triggers?view=vsts&tabs=yaml#pull-request-validation)).

**Comment by rauljmz** [comment]
I believe this is now supported. See [docs](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/triggers?view=vsts&tabs=yaml#pull-request-validation).

**Comment by mikeharder** [comment]
I agree, at least per the docs this is now supported.
