### ISSUE TITLE
View YAML for whole Pipeline

### ISSUE THREAD

**Issue by sherif-botros** [microsoft/azure-pipelines-yaml#385]
Hello,
Is there a way to view and then copy the YAML for the whole pipeline not just the Child Jobs?

**Comment by Bibz87-CG** [comment]
I'm not sure if that's what you're looking for but you might want to take a look at this [sprint update](https://docs.microsoft.com/en-us/azure/devops/release-notes/2020/pipelines/sprint-165-update#preview-fully-parsed-yaml-document-without-running-the-pipeline) entry.
