### ISSUE TITLE
Set Default Branch for Manually Queued Pipeline

### ISSUE THREAD

**Issue by doug4772** [microsoft/azure-pipelines-yaml#398]
I setup a new YAML based build which originated in my own branch.  It's since been merged into master through a PR.  The YAML build, still defaults to my branch when builds are manually queued.

I see references for setting CI and Schedule triggers by branch, but what controls the branch in the drop down selector for manually queued pipelines?  I believe I read that it uses the branch where the yaml file originated.  That seems counter intuitive in a git environment that uses PRs.

Am I missing something?

Thanks!

**Comment by doug4772** [comment]
I figured this out.  It cannot be done in the YAML itself.  The default branch for manual/scheduled builds is obscured away in the pipeline trigger settings.  It must be changed in the GUI.

**Comment by ricmatsui** [comment]
Thanks @doug4772 - I also found it via that: Pipeline > Edit > More actions > Triggers > YAML > Get sources > Default branch for manual and scheduled builds
