### ISSUE TITLE
Be able to select agent queue with matrix, similar way as container

### ISSUE THREAD

**Issue by VasiliyNovikov** [Microsoft/azure-pipelines-yaml#4]
Provide a way to select agent queues with matrix the same way as containers described here:
[Container jobs - Multiple jobs](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/container-phases?view=vsts&tabs=yaml#multiple-jobs)

Use case - I have .NET Core library that needs to be built and tested on all platforms - Windows, Linux & Mac. Right now I can solve it with [Job reuse with parameters](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/templates?view=vsts#passing-parameters) but I think matrix would be more "natural" and less verbose way to do that

Moved from here: [#1815](https://github.com/Microsoft/azure-pipelines-agent/issues/1815)

**Comment by ericsciple** [comment]
We're working on adding this scenario soon. Next one or two sprints. Our sprints are 3-weeks long, and then take another 3 weeks to roll out to all accounts.

**Comment by ericsciple** [comment]
@vtbassmatt fyi, a request for multi-job

**Comment by MSP-Greg** [comment]
@VasiliyNovikov

Agreed.  Just tried to do the same thing myself.   A 'matrix variable' seems to be visible or usable everywhere **but** when used with `vmImage`...

**Comment by mikeharder** [comment]
> @MSP-Greg we're fixing that now. We're moving `strategy` expansion earlier in the process so that it can be used with `vmImage`.

@vtbassmatt: Do you know when this new behavior should be live?  Is there an open issue tracking this work (this issue was closed 17 days ago)?

**Comment by vtbassmatt** [comment]
It slipped into this sprint, and we have 2 more weeks to go. Then it will start rolling out across the service.

**Comment by mikeharder** [comment]
@vtbassmatt: Would it make sense to re-open the issue until the fix is deployed?

**Comment by vtbassmatt** [comment]
We use these issues to discuss and track work remaining on our team. Deployments are provided for us, so there's not a lot of value in keeping a bug around waiting for that. Arguably we closed this one too early since we hadn't yet committed the code, which is leading to the extremely long delay between "issue closed" and "fix observable in practice". We'll try to be more diligent about that.

**Comment by vtbassmatt** [comment]
It's rolling out this week and into next.
