### ISSUE TITLE
How can i share builded .net core project between many jobs in Azure pipelines?

### ISSUE THREAD

**Issue by sarnecky** [microsoft/azure-pipelines-yaml#405]
I have 2 jobs. First, to restore, test, build and share build files in a build artifact. Second to pack and push nuget packages. First job finished their job with success, but second job failed during pack task. It have a problem with nuget packages, for example:

`/usr/share/dotnet/sdk/3.0.100/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(234,5): error NETSDK1064: Package Microsoft.CSharp, version 4.6.0 was not found. It might have been deleted since NuGet restore. Otherwise, NuGet restore might have only partially completed, which might have been due to maximum path length restrictions. [/home/vsts/work/1/s/src/Spotio.Leads.Client/Spotio.Leads.Client.csproj]`

https://stackoverflow.com/questions/59171421/how-can-i-share-builded-net-core-project-between-many-jobs-in-azure-pipelines

**Comment by matteotumiati** [comment]
Are you using different agents (or cleaning agent workspaces) when running these stages? I suspect that if you use, for example, hosted agents, then you may have to re-run again the NuGet package restore before running the `dotnet pack` command.
