### ISSUE TITLE
YAML multi-stage Pipeline will not authorize resources

### ISSUE THREAD

**Issue by eddie-fischer** [microsoft/azure-pipelines-yaml#410]
After creating a new YAML multi stage pipeline and a new kubernetes service connection, the pipeline is unable to authorize and use the service connection. Even when the connection is marked "Any pipeline may use this resource". The pipeline fails and says: "There was a resource authorization issue: "Pipeline does not have permissions to use the referenced service connection(s) . For authorization details, refer to https://aka.ms/yamlauthz.""

You can click 'authorize resource' which will say it succeeded but it will throw the exact same error when you run the pipeline again.

**Comment by guileinsighter** [comment]
That's also happening with previously existing (and working) yaml multi-stage pipelines. Found out about it on a demo presentation to the client's C-Level :|

**Comment by phatcher** [comment]
I have a similar use-case but when using a template, the original pipeline works and all the service connections are marked as "All pipeline" but the templated version fails with

`There was a resource authorization issue: "The pipeline is not valid. Job Job: Step Docker1 input containerRegistry references service connection $(containerRegistry) which could not be found. The service connection does not exist or has not been authorized for use. For authorization details, refer to https://aka.ms/yamlauthz.,Job Job: Step Docker2 input containerRegistry references service connection $(containerRegistry) which could not be found. The service connection does not exist or has not been authorized for use. For authorization details, refer to https://aka.ms/yamlauthz."`

Pressing the "Authorize resources" button fails.

**Comment by Saibamen** [comment]
Moved into Developer Community: https://developercommunity.visualstudio.com/content/problem/1007465/yaml-multi-stage-pipeline-will-not-authorize-resou-1.html
Please use "Follow" button on the right to track it

**Comment by Saibamen** [comment]
@eddie-fischer:
Please go to this link and answer Microsoft team: https://developercommunity.visualstudio.com/content/problem/1007465/yaml-multi-stage-pipeline-will-not-authorize-resou-1.html
