### ISSUE TITLE
Linux: Failed build completed successfully?

### ISSUE THREAD

**Issue by crazydef** [microsoft/azure-pipelines-yaml#415]
Hi,

I'm not sure when this started happening, but we've just noticed that our Linux builds are failing during the compile stage, but DevOps is claiming they passed.

Specifically, this stage in the pipeline:

```
- script: |
   cd $(Build.SourcesDirectory)/Cogs/Cogs.Rendering/Build
   ../Tools/premake5 $(Cogs.Rendering.Configuration) --cc=clang gmake2
   make -j config=$(Cogs.MakeConfig)
   ../Tools/premake5 install
  displayName: Build and Install
```

produces the following (snipped) output:

```
...
1 warning and 1 error generated.
Cogs.Rendering.make:244: recipe for target 'obj/x64/Release/Cogs.Rendering/GraphicsDeviceGL20.o' failed
make[1]: *** [obj/x64/Release/Cogs.Rendering/GraphicsDeviceGL20.o] Error 1
make[1]: *** Waiting for unfinished jobs....
1 warning generated.
9 warnings generated.
Makefile:43: recipe for target 'Cogs.Rendering' failed
make: *** [Cogs.Rendering] Error 2
Running action 'install'...
cp: cannot stat 'Debug/libCogs.Renderingd.so': No such file or directory
Finishing: Build and Install
```

Which is flagged as having succeeded, when it clearly didn't.

**Comment by denravonska** [comment]
If `premake5` isn't setting the exit code correctly then this will succeed on failure. You can try either `set -e` t the start of your script, or `failOnStdErr: true` as parameter to the script.

**Comment by crazydef** [comment]
The real issue here is there are multiple commands issued in the script, but only the return code of the last command is checked (I think).

Both the `make` and `premake install` commands fail, but their exit codes are seemingly ignored.  (It's possible our install command for premake isn't working correctly, but in this instance I wouldn't have expected that to even have been run in the first place.

I worked around this particular issue by removing the `premake install` command from the script - it was actually a superfluous step in this instance.  The exit code from `make` was then recognised correctly and the build was marked as failed.

However, I would still have preferred it if exit codes from all script commands were caught and the script terminated upon failure accordingly.

**Comment by denravonska** [comment]
That's what `set -e` will do. It exits on the first non-successful return code. If you need to execute all the steps regardless of mid-failures and then fail on exit it gets trickier as the return codes are hidden inside your post-make script.

**Comment by crazydef** [comment]
Ah, I see.  :)
