### ISSUE TITLE
Add support for 'dependsOn' for individual matrix jobs

### ISSUE THREAD

**Issue by zmurphy-ms** [microsoft/azure-pipelines-yaml#420]
I wanted to follow up on this comment from https://github.com/microsoft/azure-pipelines-yaml/issues/20#issuecomment-431893103.

> Hmm, I need to think more about dependsOn. I thought you could "reach into" the matrix and depend on a single resulting job, but if not, then no reason to introduce that here. (In fact, this would likely be implemented as syntactic sugar on top of matrix, so we'd get the exact same level of support.)

I don't see a way to "reach into" the matrix and depend on a single resulting job. If there is a way, I'd love to hear it. If not, adding that syntactic sugar for this would be helpful.

Example pipeline:
```
stages:
- stage: A
  jobs:
  - job: Build
    strategy:
      matrix:
        Release:
          Configuration: Release
        Debug:
          Configuration: Debug

    steps:
    - script: |
        echo JobName = $(System.JobName)
        echo JobDisplayName = $(System.JobDisplayName)

  - job: Test
    strategy:
      matrix:
        Release:
          Configuration: Release
        Debug:
          Configuration: Debug
    # These 'dependsOn' options give a syntax error.
    # dependsOn: "BuildRelease"
    # dependsOn: "Build Release"
    # dependsOn: "Build.Release"
    # dependsOn: "A Build Release"
    # dependsOn: "Build $(System.JobName)"
    # dependsOn: "Build $(System.JobDisplayName)"

    steps:
    - script: |
        echo JobName = $(System.JobName)
        echo JobDisplayName = $(System.JobDisplayName)
```

**Comment by Saibamen** [comment]
Moved into Developer Community: https://developercommunity.visualstudio.com/idea/1007464/support-for-dependson-for-individual-matrix-jobs.html
Please use "Follow" button on the right to track it

**Comment by martingalvan-nordic** [comment]
+1 to this. This is an extremely useful feature, esp. when the matrix items are builds donde on different OSs, architectures, etc which can be later tested individually regardless of what happened to the rest.

**Comment by oggy22** [comment]
+1 to this. Our pipelines would benefit in performance if this feature was available.
