### ISSUE TITLE
Pool condition from pipeline runtime variable

### ISSUE THREAD

**Issue by migheorghe** [microsoft/azure-pipelines-yaml#424]
Input:
- pipeline configured with the yaml bellow
- a variable named "PipelineVariable" in Azure DevOps define on the pipeline itself

Case 1) The pipeline is ran with PipelineVariable containing a string the test pool will be set with the name accordingly. Behavior: as expected

Case 2) The pipeline is ran with PipelineVariable empty (value deleted before run) there is an error 
" _##[error]The pipeline is not valid. Either a pool ID or name is required._" and in the job details is deisplayed "_PipelineVariable : undefined_"
Expected: Job should be run on azure hosted agents

_variables:
  TestsPoolName: $(PipelineVariable)
jobs:
  - job: TestAgentPools
    pool:
      ${{ if eq(variables.TestsPoolName, '') }}:
        vmImage: windows-2019
      ${{ if ne(variables.TestsPoolName, '') }}:
        name: ${{ variables.TestsPoolName }}
      demands:
      - npm
    steps:
      - powershell: |
          Write-Host "Variables for current build:"
          Get-ChildItem ENV:*
        displayName: "Print variables"
        continueOnError: true
        condition: always()

**Comment by ShreyasRmsft** [comment]
Adding @zachariahcox to take a look.

**Comment by zachariahcox** [comment]
@migheorghe , are you saying you queued a build where the TestPoolName queue-time variable input was left empty? 
@azureDaveOps, what happens to queue-time variables if users delete the content?

**Comment by migheorghe** [comment]
Hi,

In the example bellow only the condition on the "StaticVar" works. All other conditions, no matter their values, cause the exception _" ##[error]The pipeline is not valid. Either a pool ID or name is required."_
The _"PipelineVariable"_ is set in Azure DevOps interface on the CI pipeline (so not in yml file), with override check activated. I was expecting the same behavior from it as it is from _"StaticVar"_

variables:
  TestsPoolName: $(PipelineVariable)
  StaticVar: 'azure'
jobs:
  - job: TestAgentPools
    pool:
      ${{ if eq(variables.TestsPoolName, 'Hosted') }}:
        vmImage: windows-2019
      ${{ if eq(variables.TestsPoolName, 'SelfHosted') }}:
        name: ${{ variables.TestsPoolName }}
      demands:
      - npm
    steps:
      - powershell: |
          Write-Host "Variables for current build:"
          Get-ChildItem ENV:*
        displayName: "Print variables"
        continueOnError: true
        condition: always()

  - job: TestAgentPools2
    pool:
      ${{ if eq(variables.PipelineVariable, 'Hosted') }}:
        vmImage: windows-2019
      ${{ if eq(variables.PipelineVariable, 'SelfHosted') }}:
        name: ${{ variables.PipelineVariable }}
      demands:
      - npm
    steps:
      - powershell: |
          Write-Host "Variables for current build:"
          Get-ChildItem ENV:*
        displayName: "Print variables"
        continueOnError: true
        condition: always()



  - job: TestAgentPools3
    pool:
      ${{ if eq(variables.StaticVar, 'azure') }}:
        vmImage: windows-2019
      ${{ if eq(variables.StaticVar, 'somethingnotequal') }}:
        name: ${{ variables.StaticVar }}
      demands:
      - npm
    steps:
      - powershell: |
          Write-Host "Variables for current build:"
          Get-ChildItem ENV:*
        displayName: "Print variables"
        continueOnError: true
        condition: always()

**Comment by migheorghe** [comment]
@zachariahcox @jeschu1 can you help? Do you need extra info?
Static vars on the pipeline don't behave the same as static vars inside yaml at parsing....

**Comment by spoelstraethan** [comment]
You can use a slightly different approach, there are several outlined in this SO post.

https://stackoverflow.com/a/76075535/3794873
