### ISSUE TITLE
Overwriting readonly task variable 'agent.jobstatus'. Alternative

### ISSUE THREAD

**Issue by Cellule** [microsoft/azure-pipelines-yaml#439]
I've just noticed the following warning in my pipeline
```
##[warning]Overwriting readonly task variable 'agent.jobstatus'. This behavior will be disabled in the future. See https://github.com/microsoft/azure-pipelines-yaml/blob/master/design/readonly-variables.md for details.
```

As far as I know, DevOps hasn't provided a good way to cancel a build from a task.
The only options I found were
- Set a variable and have ALL subsequent task check the variable (honestly I'm not ever doing this again, it's way too error prone and painful)
- Change the `agent.jobstatus` variable to `canceled`

```
  echo "##vso[task.setvariable variable=agent.jobstatus;]canceled"
  echo "##vso[task.complete result=Canceled;]DONE"
```

This allows me to check if files were changed in certain paths in my git repo and if not I skip the build. Path filters on build trigger is NOT a viable option.
It has saved considerable build and dev time by making this change.

Now I am worried that readonly variable will remove the ability to cancel jobs (for whatever reason, path change is just 1 example).

If readonly variables go forward, what solutions can you provide to allow to cancel a job?

**Comment by damccorm** [comment]
You should be able to do this by hitting an endpoint - https://docs.microsoft.com/en-us/rest/api/datafactory/pipelineruns/cancel

With that said, this is a bit of a weird pattern; our canceled state generally means "cancelled by user" - this is actually an explicit decision on our end https://github.com/microsoft/azure-pipelines-tasks/pull/11845 - so I don't see us officially supporting this via a task or an agent primitive.

cc/ @vtbassmatt to fact check me on this one

**Comment by Cellule** [comment]
> You should be able to do this by hitting an endpoint - https://docs.microsoft.com/en-us/rest/api/datafactory/pipelineruns/cancel

The problem is that would cancel the whole pipeline, I have 10 different jobs running in a single pipeline. I have 1 pipeline for PR validation which build/tests a bunch of various folder/project in the monorepo.

I don't especially need the build to be "canceled", simply that it will stop running further tasks and not be marked as failed.

**Comment by Cellule** [comment]
Even if I split the various build in a separate pipeline (which I really would like to avoid), I still wouldn't be able to precisely determine whether to process the build or not (like I mentioned before, path filters on builds is not precise enough).
Additionally, once all my checks are completed, I need to run a release, only when ALL the checks are completed.

I'm not even sure I can mark a release to combine multiple build into 1 release and make sure they're all present AND using the same commit hash.
Assuming that's possible, I'm pretty sure path filters would break that.

From my research when I was looking into a way to cancel builds from a task, I can tell there were a lot of people relying on canceling `agent.jobstatus` leaving all those people without any alternative mechanism.

Maybe instead of "cancel" it could expose a function to `skip` the rest of the build or mark it `passed`, but not processing any further tasks.
Something like
```
echo "##vso[build.complete result=Succeeded;]"
```

**Comment by vtbassmatt** [comment]
You can't cancel a single job, because what would that mean for the broader pipeline's status? @damccorm is correct that cancellation is generally user initiated. It also must come from the server (hence the suggestion to call the cancel API) so that it fans out across all running and future jobs. There is also no "early return" concept for a job, though I'm not opposed to that one in principle.

The correct way to implement this pattern is to do your check, set a variable (if single-job) or output variable (if the answer affects multiple jobs), and check that variable in the condition for subsequent tasks. Something like:

```yaml
steps:
- script: |
    # compute "should I continue" somehow
    echo ##vso[task.setVariable variable=continue]true
- task: foo@1
  condition: and(succeeded(), eq(variables.continue, 'true'))
- task: bar@1
  condition: and(succeeded(), eq(variables.continue, 'true'))
```

Overwriting system variables was never supported and was always documented as not working. We didn't always enforce that in the context of a single job, which was a mistake on our part. The correct way to change a job's status is to use `##vso[task.complete]` (and if one went through that supported path, it would be obvious that the job can't be canceled - that was correctly blocked).

**Comment by Cellule** [comment]
> The correct way to implement this pattern is to do your check, set a variable (if single-job) or output variable (if the answer affects multiple jobs), and check that variable in the condition for subsequent tasks. Something like:

I have gone down that route in the past and honestly it's a real mess, whenever you have more than a handful of task and/or task group, it becomes really hard to read and reason how the tasks behave and make sure to not forget any of the tasks to check that variable.
Maybe it's easier to see in yaml, but I'm still using classic editor for the pipeline.

I completely understand your stance on cancelling and in a lot ways I agree.
I used cancel really only because it was the only method I could find for an early return/completion of a build on a specific agent.

**Comment by vtbassmatt** [comment]
I re-read what I wrote, and I realized it may not have come across exactly how I meant it. First of all, thanks for the feedback! I agree that this is way easier to see in YAML and doesn't map very well to classic.

Let me do some thinking about an "early cancel" function, which would solve a lot of people's problems here without overcomplicating our model.

**Comment by Cellule** [comment]
Thanks!
I'm not sure why you closed the issue, but I hope you'll keep me posted.


I'm don't think I still have access, but I remember having to do something similar when I was working on Chakra.
You might be able to access their [build definitions](https://chakrateam.visualstudio.com/Push_Build_Runner/_build/latest?definitionId=50&branchName=master)
https://github.com/microsoft/ChakraCore
I did use the solution of setting a variable and having every task check that variable

**Comment by vtbassmatt** [comment]
There's not much value in keeping this open; we don't track backlog items in this repo.

**Comment by Cellule** [comment]
So the readonly change was shipped and no solution for an early return has been provided. Now all my jobs trying to stop are failing. 

Please tell me you considered an alternative to support this use case?

**Comment by beatcracker** [comment]
Could this be configurable? I'm currently overwriting `Build.SourceBranch` because I need GitVersion extension to run against a repo that I additionally check out. GitVersion uses this variable to get target branch when run with `/output buildserver` and and there is no other way to set it this case. 

This setup is a part of our unit test for GitVersion to make sure that changes to it's configuration file(s) do not bring in unforeseen consequences across multiple repos. To simulate the real build environment I need to run this as an extension which uses  `/output buildserver` and not just script around it.

**Comment by vtbassmatt** [comment]
@AArnott might be able to take a feature request for GitVersioning (I'm assuming that's the one you mean).

Nothing stops you from overwriting the environment variable itself for a given step. We just won't let you alter the underlying pipeline variable. Something like:

```yaml
steps:
- task: GitVersioning@1
  inputs:
    foo: bar
  env:
    BUILD_SOURCEBRANCH: (your preferred value)
```

**Comment by Cellule** [comment]
Here's my current solution:

For Pull Request Validation:
- For every place I would normally cancel the build, create a new pipeline and use Path Filters and PR triggers to determine if the pipeline should run
- For me this meant breaking down my 1 pipeline with 5 jobs into 11 pipelines (1 with 2 jobs)

For Continuous integration, I couldn't use that strategy because I need to trigger a release after the build (couldn't find a way to make a release depend on multiple builds with path filters).
So instead I have 1 pipeline that checks for files changed in various folder and adds Build Tag to the build.
Then I defined my release to trigger depending on the build tags and various stages depend on individual build tag to do build & tests then have a gated deployment

**Comment by beatcracker** [comment]
> @AArnott might be able to take a feature request for GitVersioning (I'm assuming that's the one you mean).

Sorry, should've make it clear: https://github.com/GitTools/GitVersion . It has three extensions:

- Deprecated: https://marketplace.visualstudio.com/items?itemName=gittools.gitversion
- Stable: https://marketplace.visualstudio.com/items?itemName=gittools.usegitversion
- vNext: https://marketplace.visualstudio.com/items?itemName=gittools.gittools

I'm in the middle of figuring out migration paths from GitVersion 4.x (no extension, runs as a part of build script) and "Deprecated" to "Stable" or "vNext".

> Nothing stops you from overwriting the environment variable itself for a given step. We just won't let you alter the underlying pipeline variable.

That would be awesome, unfortunately I just tested it and it doesn't work:

```yml
- task: gittools.gitversion.gitversion-task.GitVersion@5
  displayName: GitVersion
  inputs:
    configFilePath: $(config)
    additionalArguments: /targetpath $(target_path)
  continueOnError: true
  env:
    BUILD_SOURCEBRANCH: refs/heads/FOO
    BUILD_SOURCEBRANCHNAME: FOO
```

Result:

```none
Applicable build agent found: 'VsoAgent'.
Branch from build environment: refs/heads/feature/some-branch
```

The code reading env. var in GitVersion is [pretty simple](https://github.com/GitTools/GitVersion/blob/660454f38a7b41aec3221b2480310f67ee5ff2ae/src/GitVersionCore/BuildServers/AzurePipelines.cs#L30), so I guess something else is going on.

**Comment by beatcracker** [comment]
Tested with `bash` task - no luck:

```yml
- bash: |
    echo "BUILD_SOURCEBRANCH: $BUILD_SOURCEBRANCH"
    echo "BUILD_SOURCEBRANCHNAME: $BUILD_SOURCEBRANCHNAME"
  env:
    BUILD_SOURCEBRANCH: refs/heads/FOO
    BUILD_SOURCEBRANCHNAME: FOO
```

Result:

```none
##[debug]noProfile=true
##[debug]noRc=true
##[debug]check path : /home/vsts/work/_tasks/Bash_6c731c3c-3c68-459a-a5c9-bde6e6595b5b/3.163.1/task.json
##[debug]adding resource file: /home/vsts/work/_tasks/Bash_6c731c3c-3c68-459a-a5c9-bde6e6595b5b/3.163.1/task.json
##[debug]system.culture=en-US
##[debug]failOnStderr=false
##[debug]workingDirectory=/home/vsts/work/1/s
##[debug]check path : /home/vsts/work/1/s
##[debug]targetType=inline
##[debug]script=echo "BUILD_SOURCEBRANCH: $BUILD_SOURCEBRANCH"
echo "BUILD_SOURCEBRANCHNAME: $BUILD_SOURCEBRANCHNAME"
Generating script.
##[debug]which 'bash'
##[debug]found: '/bin/bash'
##[debug]Agent.Version=2.165.0
##[debug]agent.tempDirectory=/home/vsts/work/_temp
##[debug]check path : /home/vsts/work/_temp
========================== Starting Command Output ===========================
##[debug]which '/bin/bash'
##[debug]found: '/bin/bash'
##[debug]/bin/bash arg: --noprofile
##[debug]/bin/bash arg: --norc
##[debug]/bin/bash arg: /home/vsts/work/_temp/ba9f22f7-83e2-4293-95a9-378d42222d0c.sh
##[debug]exec tool: /bin/bash
##[debug]arguments:
##[debug]   --noprofile
##[debug]   --norc
##[debug]   /home/vsts/work/_temp/ba9f22f7-83e2-4293-95a9-378d42222d0c.sh
/bin/bash --noprofile --norc /home/vsts/work/_temp/ba9f22f7-83e2-4293-95a9-378d42222d0c.sh
BUILD_SOURCEBRANCH: refs/heads/feature/some-branch
BUILD_SOURCEBRANCHNAME: some-branch
```

**Comment by jtpetty** [comment]
@vtbassmatt - I think in the agent, we convert pipeline variables to environment variables after we set the supplied environment variables for a task.

**Comment by vtbassmatt** [comment]
@jtpetty d'oh, didn't realize that.

@beatcracker I can temporarily disable this change in your account while you figure out an upgrade strategy. What's your organization name? (That would be `https://dev.azure.com/<orgname>`.)

**Comment by beatcracker** [comment]
@vtbassmatt I'm not clear on how this feature is rolled out: currently I only get warnings, but it still works. However if you could postpone cut-off, that would be fantastic. Would you mind if I drop you an email on `vtbassmatt@gmail.com` (or any other address) ? I'd rather not share an organization name here.

@jtpetty Thanks, that's pretty much explains it. Is there any chance that I could create an issue on this, so this behavior could be changed?

**Comment by vtbassmatt** [comment]
Hey @beatcracker you can email my work address, mattc@xbox.com, with your org name.

We're probably not going to change the variable override behavior. Despite the fact that I didn't know the precise details, I can virtually guarantee there are [dozens of customers depending on the exact behavior](https://www.hyrumslaw.com/) today.

**Comment by AArnott** [comment]
> I think in the agent, we convert pipeline variables to environment variables after we set the supplied environment variables for a task.

That still shouldn't stop you from defining env vars *within* the task itself. Like this:

```yml
- bash: |
    export BUILD_SOURCEBRANCH=refs/heads/FOO
    export BUILD_SOURCEBRANCHNAME=FOO
    echo "BUILD_SOURCEBRANCH: $BUILD_SOURCEBRANCH"
    echo "BUILD_SOURCEBRANCHNAME: $BUILD_SOURCEBRANCHNAME"
```

**Comment by pwen090** [comment]
I just want to clarify that if I have a pipeline with say 15 tasks but on the 5th task I check some value that determines that I do not want to proceed further that I now have to set and check a variable in the subsequent 10 tasks and remember to do that on any next task I create? There is no way to cancel or return success early without running through every task? I guess we could have two agent jobs and have the second job check a variable from the first and not run but that is also cumbersome because variables/task work from the first job I would have to duplicate in the second job because of the separation of data in jobs.

**Comment by vtbassmatt** [comment]
The execution model is that each step gets a shot at executing and makes its own decisions about what to do. So, there's no one-liner to model an early, successful return. If it helps, keep in mind that every step already has a default condition it's checking. That condition is `succeeded()`. Your override would be `and(succeeded(), not(eq(variables['mycheckvar'], 'true')))`.

**Comment by pwen090** [comment]
It seems having two agent jobs should clean it up once we can switch to yaml and pass variables between jobs. Thank you @vtbassmatt  !

**Comment by ahhlun** [comment]
@vtbassmatt you mentioned "Let me do some thinking about an "early cancel" function, which would solve a lot of people's problems here without overcomplicating our model."

Have you thought about it? Seems like a lot of people are requesting this feature.
The suggestion of using `and(succeeded(), not(eq(variables['mycheckvar'], 'true')))`
is cumbersome in classic.

**Comment by vtbassmatt** [comment]
We discussed it and thought through some designs. It doesn't rank on our current list of priorities unfortunately.

**Comment by jasondavidcamp** [comment]
Is there a way to turn off this behavior that stops BUILD_SOURCEBRANCH from being modified on Azure DevOps Server 2022 Update 2 patch 1?
