### ISSUE TITLE
Multi-tenant deployments or stages

### ISSUE THREAD

**Issue by rnarayana** [microsoft/azure-pipelines-yaml#441]
Hi,
Is there a way or plan to support multi-tenanted deployments to the same environment, something like this:
![image](https://user-images.githubusercontent.com/203111/73707020-357afe80-4720-11ea-8ae4-19914537c160.png)

If not, how can I achieve this in the best possible way today?

**Comment by rnarayana** [comment]
One way I can think of is Adding one Build pipeline, and then multiple pipelines to deploy, one for each tenant, but all based off the same YAML file. This would work like how I have described it above.

**Comment by PaulVrugt** [comment]
yeah thats not really workable if you have hundreds of tenants. Any other solution? In Octopus deploy tenants can be registered and we can deploy to separate tenants, and have a variable set per tenant. Is there anything similar in yaml pipelines?
