### ISSUE TITLE
Set deployment job environment and resource name as variable

### ISSUE THREAD

**Issue by szymon-edlund** [microsoft/azure-pipelines-yaml#449]
I would like suggest to implement deployment job environment properties as variable (for virtual machine resources).

The prefer way of use should be like this
`- deployment: deploy_lifelink
    displayName: 'Deploy LifeLink'
    dependsOn: initialize_variables
    variables:
      environmentName: $[dependencies.initialize_variables.outputs['initialize_variables.environmentName']]
      virtualMachineName: $[dependencies.initialize_variables.outputs['initialize_variables.virtualMachineName']]
    environment:
      name: $(environmentName)
      resourceName: $(virtualMachineName)`

**Comment by akokskis** [comment]
+1 - I'd love to see this functionality.
