### ISSUE TITLE
Support configurable display names

### ISSUE THREAD

**Issue by CoolDadTx** [microsoft/azure-pipelines-yaml#45]
Copied from: https://github.com/MicrosoftDocs/vsts-docs/issues/2327

It would be nice if you could dynamically set the display name of a task. This would allow the build logs to show information more relevant to the build.

For example you might have a build task that generates a version number for the build. It would be nice to be able to see the version number in the log summary by updating the display name. This would require the display name to be able to reference parameters, variables, env vars or something equivalent that preceding steps could set.

Based upon the link given above it is possible by using separate jobs. But I'd like to see this support added directly so we don't have to create separate jobs just to set the display name.

**Comment by marcinma** [comment]
It would also great having this as "description" or "display" name of current released pipeline (consider releasing list of different app versions)
