### ISSUE TITLE
Multiple repo checkout with branch name passed dynamically

### ISSUE THREAD

**Issue by msarathc-ms** [microsoft/azure-pipelines-yaml#450]
I want to be able to checkout multiple respositories with dynamic branch name variable. Below is the snippet from pipeline yaml file. 

Here, the pipeline fails stating that this branch "$(BranchNameVariable)" does not exist. It seems like the pipeline is not waiting to execute the previous step before checking out the second repository. 

        steps:
          - checkout: 'self'
          - task: Bash@3
            displayName: Identify target branch name
            inputs:
              targetType: 'inline'
              script: |
                #!/usr/bin/ksh
                targetBranch='master';
                
                # logic goes here to identify the branch name set to 
                # targetBranch variable dynamically. like $targetBranch=feature/123
                
                echo "##vso[task.setvariable variable=BranchNameVariable]$targetBranch";
          - checkout: git://$(System.TeamProjectId)/AnotherRepo@$(BranchNameVariable)

**Comment by KenjiYokoyama** [comment]
I also hope this feature.  
When compare between a current branch and a merged branch in a snapshot testing in a pipeline triggered by a pull request, the current branch has to be checked out by specifying a variable **"System.PullRequest.TargetBranch"**.

\# If using variables is difficult, the following way is also fine in my case...  

```yaml
- checkout: self@${{variables['System.PullRequest.TargetBranch']}}
```

**Comment by ttsakpc** [comment]
> # If using variables is difficult, the following way is also fine in my case...
> 
> ```yaml
> - checkout: self@${{variables['System.PullRequest.TargetBranch']}}
> ```

I needed the same thing and the only solution I found was to add a manual `git checkout` step after the `checkout: self` step (following your example):

```yaml
- checkout: self
- script: git checkout ${{variables['System.PullRequest.TargetBranch']}}
```

The downside is that the run status shows that the pipeline was executed for the "default" branch instead of the branch that was actually used because of the script. But other than that, it works
