### ISSUE TITLE
Deployment queue settings support

### ISSUE THREAD

**Issue by Bibz87-CG** [microsoft/azure-pipelines-yaml#454]
Is there a way to have the same behavior as classic pipelines' _Deployment queue settings_? We noticed our YAML pipelines will still deploy on environments even if there's an earlier pipeline execution awaiting approval or already deploying on the same environment.

Is this something we can implement in YAML pipelines?

![image](https://user-images.githubusercontent.com/45204505/75361102-c8710980-5884-11ea-87a2-093e198b2c0c.png)

**Comment by Gerrit-K** [comment]
To anyone else searching: the stale-bot link isn't really helpful, but I found this:

[Developer Community - Bring queuing policies to YAML multistage pipelines](https://developercommunity.visualstudio.com/idea/776356/bring-queuing-policies-to-yaml-multistage-pipeline.html)

Hope this gets addressed soon.

**Comment by matteotumiati** [comment]
I guess it doesn't cover 100% of the feature in release management, but something has been released already as part of Sprint 172:
https://docs.microsoft.com/en-us/azure/devops/release-notes/2020/sprint-172-update#exclusive-deployment-lock-policy
