### ISSUE TITLE
Feature request - Warning when overriding pre-defined pipeline variables (e.g., PATH)

### ISSUE THREAD

**Issue by amasover** [microsoft/azure-pipelines-yaml#468]
Hello. I created a pipeline that looks like this:

```yaml
jobs:
  - job: myJob
    variables:
      path: "examplePath"
    steps:
      - bash: echo hello
```

Upon running the pipeline, I got the following error:

```
##[error]Unable to locate executable file: 'bash'. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also check the file mode to verify the file is executable.
```

I couldn't figure out why I was getting the error until I realized, of course, that the `path` variable ends up in the environment of the "Bash" task as `$PATH`. It is an incredibly obvious mistake on my part in hindsight, but I think it's maybe not completely intuitive that Azure Pipelines works this way.

To get my pipeline working, I simply chose to not use `path` as an input variable name. But I think perhaps printing a warning when a user overrides a pre-defined variable would save time for others if they run into something like this.

Another option could be to make `path` a read-only variable. But then again, I think there are valid use-cases for wanting to override the path.

**Comment by vtbassmatt** [comment]
In order to consolidate to fewer feedback channels, we've moved suggestions and issue reporting to [Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html). Sorry for the delay/confusion.

**Comment by amasover** [comment]
[I've created this feature request within the Developer Community.](https://developercommunity.visualstudio.com/idea/1033298/warning-when-overriding-pre-defined-pipeline-varia.html)
