### ISSUE TITLE
Extending Pipeline Starter Templates

### ISSUE THREAD

**Issue by rafiwardak2003** [microsoft/azure-pipelines-yaml#473]
I am trying to write a custom extension that when you try to create a new build pipeline, say for Angular, you would get an option for this custom pipeline which would generate the complete script that our organization needs. (Very similar to the Microsoft-provided Angular starter template)

Is this possible, or are only build/release tasks allowed to be customized? I don't really want someone to create an empty Yaml template and then have them add my custom task if I can actually generate the entire Yaml for them, which would have jobs, references to other templates, etc.

I want my custom extension to show up here, like one of these:
![image](https://user-images.githubusercontent.com/17308146/78354070-29bd8400-7579-11ea-868f-fd1a81a23819.png)

**Comment by vtbassmatt** [comment]
In order to consolidate to fewer feedback channels, we've moved suggestions and issue reporting to [Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html). Sorry for the delay/confusion.
