### ISSUE TITLE
Azure pipelines is formatting all the output with ***

### ISSUE THREAD

**Issue by haripraghash** [microsoft/azure-pipelines-yaml#475]
Hi All,

I have an azure pipeline that is defined using YAML.

All the logs that is being output, is being masked with "***".

[azure-pipelines.zip](https://github.com/microsoft/azure-pipelines-yaml/files/4428303/azure-pipelines.zip)

[log.txt](https://github.com/microsoft/azure-pipelines-yaml/files/4428308/log.txt)

**Comment by matteotumiati** [comment]
I'm not really sure what's going on, but I've seen this behavior before when creating any pipeline (not only YAML) executing scripts with secure strings. Perhaps this is something to be logged as a bug here? https://developercommunity.visualstudio.com/

**Comment by vtbassmatt** [comment]
We aren't doing product support or issue reporting in this repo. Please open a ticket at [Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html). Sorry for the delay/confusion.
