### ISSUE TITLE
how to suppress warnings from console output

### ISSUE THREAD

**Issue by tsaibabu4u** [microsoft/azure-pipelines-yaml#476]
I am unable to suppress warnings from azure pipeline logging. do we have any workaround to suppress those ?

**Comment by vtbassmatt** [comment]
In order to consolidate to fewer feedback channels, we've moved suggestions and issue reporting to [Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html). Sorry for the delay/confusion.
