### ISSUE TITLE
Prevent deployment if previous stage deployment condition is set to false in yaml

### ISSUE THREAD

**Issue by xyz92** [microsoft/azure-pipelines-yaml#477]
I created a build/release pipeline using yaml:

[![enter image description here][1]][1]

Here, the first stage is 'Build'. Once Build is complete and succeeded, next stage is 'deploy to ua'. If deployment to ua is complete and succeeded, next stage is 'deploy to prod'.

As shown here, the condition for 'deployment to ua' returned a 'false'. Even if condition in 'deploy to ua' returned false, 'deploy to prod' started. How would I skip 'deployment to prod' if the condition for 'deployment to ua' is false?

In prod,  I have provided the following:

```
dependsOn: 
    - Deploy_Service_ua
```

[![enter image description here][2]][2]

  [1]: https://i.stack.imgur.com/2Fb6a.png
  [2]: https://i.stack.imgur.com/hhS76.png

**Comment by vtbassmatt** [comment]
In order to consolidate to fewer feedback channels, we've moved suggestions and issue reporting to [Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html). Sorry for the delay/confusion.
