### ISSUE TITLE
timeoutinMinutes doesn't work for single job format

### ISSUE THREAD

**Issue by geofflamrock** [microsoft/azure-pipelines-yaml#48]
When using the full syntax for jobs the timeoutInMinutes can be set at the same level as the job. From the docs:

```
jobs:
- job: string
  timeoutInMinutes: number
  cancelTimeoutInMinutes: number
  strategy:
    maxParallel: number
    # note: `parallel` and `matrix` are mutually exclusive
    # you may specify one or the other; including both is an error
    parallel: number
    matrix: { string: { string: string } }
  pool:
    name: string
    demands: string | [ string ]

  container: string

  steps:
    - script: echo Hello world
```

However if I set it when using the single-job syntax the build pipeline fails with error "Unexpected value 'timeoutInMinutes'"

If I move the timeoutInMinutes into the pool element it works ok.

If this is by design then it might be worth updating the docs to indicate this.

Thanks :)

**Comment by mikeharder** [comment]
I do see a few places in the docs which specify the single-job format implies default options:

> Note: If you have only one job, you can use single-job syntax which **omits many of the keywords here**.
https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema#job

> You can skip the job syntax if you need only a single job **with the standard options**.
https://docs.microsoft.com/en-us/azure/devops/pipelines/process/phases?tabs=yaml&view=azure-devops

**Comment by geofflamrock** [comment]
Thanks @mikeharder I guess my point was more that in the full syntax the `timeoutInMinutes` lives at the top level within a job, so I was expecting it to live at the same level in the single job syntax but it doesn't, it lives in `pool` of which there is no mention in the docs. Other properties in the full syntax work the same way in the single syntax but this property doesn't.

**Comment by Madushani** [comment]
given below is content of my yaml.xml file
trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: false
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'integration-test'

Note: this works fine if I set the goals as  goals: 'integration-test'. 

But given configuration fails returning following errors
The agent has received a shutdown signal. This can happen when the agent service is stopped, or a manually started agent is canceled.
The job exceeded the maximum allowed time of 01:00:00 and was stopped. Please visit &lt;a href='https://go.microsoft.com/fwlink/?linkid=832649' target='_blank' &gt;parallel jobs&lt;/a&gt; for more information.
The operation was canceled.


so I wanted to increate timeoutinMinutes and modified as follows

trigger:
- master

jobs:
- job: my job
  timeoutInMinutes: 120
  cancelTimeoutInMinutes: 2
  strategy:
    maxParallel: 3
    # note: `parallel` and `matrix` are mutually exclusive
    # you may specify one or the other; including both is an error
    #parallel: 2
    matrix: { string: { string: string } }
  pool:
    name: 'test3'
    vmImage: 'ubuntu-latest'  

 steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: false
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'ntegration-test' 

result in throwing error as : 
Unexpected value 'steps'

Can somebody how to guide me to fix this?

**Comment by Madushani** [comment]
trigger:
- master

jobs:
  - job: Package
    timeoutInMinutes: 120

    pool:
     name: 'Hosted Ubuntu 1604'

    steps:
    - task: Maven@3
      inputs:
        mavenPomFile: 'pom.xml'
        mavenOptions: '-Xmx3072m'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '1.8'
        jdkArchitectureOption: 'x64'
        publishJUnitResults: false
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        goals: 'install'


It still throwing these errors
Job issues

The agent has received a shutdown signal. This can happen when the agent service is stopped, or a manually started agent is canceled.

**Comment by Saibamen** [comment]
Related: https://github.com/Microsoft/azure-pipelines-agent/issues/1849

**Comment by Saibamen** [comment]
I have a question: @geofflamrock says: `If I move the timeoutInMinutes into the pool element it works ok.`,
@lukeschlather: `It's accepted under the pool key but it seems to have no effect. It seems impossible to set a timeout with the standard single-job format.`

So: How to change timeout in any possible way? With example, please. I don't care it is for all pipeline or one/two/three jobs.

**Comment by Saibamen** [comment]
Moved into Developer Community by me: https://developercommunity.visualstudio.com/content/problem/1007432/timeoutinminutes-doesnt-work-for-single-job-format.html

**Comment by Saibamen** [comment]
@geofflamrock:
Please go to this link and answer Microsoft team: https://developercommunity.visualstudio.com/content/problem/1007432/timeoutinminutes-doesnt-work-for-single-job-format.html

**Comment by geofflamrock** [comment]
Thanks @Saibamen I've tested and it's now working as documented, I've replied back on the other link.
