### ISSUE TITLE
Passing parameter values from commit message

### ISSUE THREAD

**Issue by yelkarama** [microsoft/azure-pipelines-yaml#480]
For a CI build pipeline that is triggered by code pushes, is there a way to read parameter values directly from the commit message ?

**Comment by ArtjomP** [comment]
You have Build.SourceVersion variable that contains commit id. Having this id you can use git commands to read the message.

**Comment by vtbassmatt** [comment]
In order to consolidate to fewer feedback channels, we've moved suggestions and issue reporting to [Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html). Sorry for the delay/confusion.
