### ISSUE TITLE
Is `autoCancel: false`  feature working?

### ISSUE THREAD

**Issue by stephenmoloney** [microsoft/azure-pipelines-yaml#481]
Hi,

I've set the feature `autoCancel: false` on the `pr` trigger.

But the jobs are all still being cancelled with the next pushed commit to the PR. Was there are breaking change - does this feature work?

```yaml
pr:
  autoCancel: false
```

**Comment by vtbassmatt** [comment]
In order to consolidate to fewer feedback channels, we've moved suggestions and issue reporting to [Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html). Sorry for the delay/confusion.
