### ISSUE TITLE
Multi projects in same repo with their own pipeline

### ISSUE THREAD

**Issue by jmezach** [microsoft/azure-pipelines-yaml#484]
This isn't necessarily an issue, but more of a question. My team is currently looking at consolidating multiple projects into a single repository, while still letting them have their own pipeline. I guess you could call it a mono-repo. Although this works quite well already, we've found one thing a little bit lacking, which is how paths are handled in this scenario. We've been investing in templates to simplify the creation of pipelines and those templates generally assume that the tasks they run are run from the repository root. Obviously this fails in the face of multiple projects being within the same repository because some things are just nested one level deeper down.

I guess I was somewhat naively thinking this would just work because the pipeline definition itself would be one level deeper down as well and all would be good. Unfortunately that's not how it seems to work, at least not currently. I guess I'm wondering if there are any plans to deal with this sort of thing. For now we've worked around it by extending the templates with additional optional parameters to provide a path prefix, but I guess these problems could be solved by changing the working directory altogether. As far as I can tell there currently is no way to change the working directory at the job level. You can do it for script steps, but it doesn't look supported for tasks for example.

Are there any plans to support this in a more natural way?

**Comment by vtbassmatt** [comment]
In order to consolidate to fewer feedback channels, we've moved suggestions and issue reporting to [Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html). Sorry for the delay/confusion.

There are no plans to allow changing the working directory for an entire job. Tasks which operate on files should be taking a working directory input if that's relevant to them.
