### ISSUE TITLE
Please release the YAML schema file

### ISSUE THREAD

**Issue by Meai1** [microsoft/azure-pipelines-yaml#485]
The schema can be pieced together from the [docs page ](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema%2Cparameter-schema) but it's really pointlessly labor intensive, can you please just share the full schema file somewhere, preferably right here in this repository? Or is there no actual "real" YAML schema and we should use this: https://github.com/microsoft/azure-pipelines-vscode/blob/master/service-schema.json ?

**Comment by vtbassmatt** [comment]
You can get the schema for your organization here: https://dev.azure.com/YOURORGNAME/_apis/distributedtask/yamlschema. Pay no attention to the version number in the header comment; it always claims to be sprint 147 which hasn't been true since approximately sprint 148 :grin:
