### ISSUE TITLE
Azure Pipelines trims leading and trailing \r\n from yaml strings

### ISSUE THREAD

**Issue by Calidus** [microsoft/azure-pipelines-yaml#487]
If _\r\n_ is at the being or end of a string it is removed when the pipeline is being executed. If \r\n is in the middle of a string it behaves as expected. While _`n_ seems to work correctly no matter its position in a string.

If this is working as intend it should be easier to find in the documentation.

**Comment by vtbassmatt** [comment]
In order to consolidate to fewer feedback channels, we've moved suggestions and issue reporting to [Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html). Sorry for the delay/confusion.
