### ISSUE TITLE
Condition on Step Passed as Parameter Gets Ignored

### ISSUE THREAD

**Issue by pyrostew** [microsoft/azure-pipelines-yaml#490]
I have a template that forms the core build logic for my repos. I have a parameter on the template for passing a step list to extend the job with specific logic for each repo.

The template enforces 2 build configurations, but some of the steps for extending don't need to run for both configurations.

I have tried a couple of different methods for running the steps based on the current build configuration, some of which obviously (in hindsight) won't work because of Compile time and Runtime variables.

My last attempt was to add a custom condition to the steps, but the condition seems to have no affect regardless of the expression I put in. Below are the yml files.

[BuildAndTest.yml.txt](https://github.com/microsoft/azure-pipelines-yaml/files/4517067/BuildAndTest.yml.txt)
[BuildAndPublish.yml.txt](https://github.com/microsoft/azure-pipelines-yaml/files/4517068/BuildAndPublish.yml.txt)

If someone can suggest a better method I am all ears, otherwise what am I doing wrong with this method?

**Comment by vtbassmatt** [comment]
We aren't doing product support or issue reporting in this repo. Please open a ticket at [Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html). Sorry for the delay/confusion.
