### ISSUE TITLE
Any documentations to shortGuid/toAlphaNumericString

### ISSUE THREAD

**Issue by jizusun** [microsoft/azure-pipelines-yaml#501]
Hi team,

I really love the product and this template, but I cannot find anything on the Internet about `shortGuid` and `toAlphaNumericString`.

https://github.com/microsoft/azure-pipelines-yaml/blob/24d2dd873fdecc0b49cca8bd860eff9ab5fe285c/templates/deploy-to-existing-kubernetes-cluster-devspaces.yml#L15-L19

Where can I find such information?

Thanks so much ❤️ 

Best regards,
Jizu

**Comment by jizusun** [comment]
> In order to consolidate to fewer feedback channels, we've moved suggestions and issue reporting to [Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html). Sorry for any confusion resulting from this move.

I cannot find any information about this in that forum

**Comment by TheYorkshireDev** [comment]
@jizusun Did you find out any further infomation/documentation about `shortGuid` and `toAlphaNumericString`?

**Comment by jizusun** [comment]
> Hey, @jizusun Did you find out any further information/documentation about `shortGuid` and `toAlphaNumericString`?

No ...
