### ISSUE TITLE
properties.json spec?

### ISSUE THREAD

**Issue by blake-mealey** [microsoft/azure-pipelines-yaml#526]
After looking into this project a bit I've noticed you're using `template-name.properties.json` files to add metadata for your templates. This seems quite similar to GH actions properties.json files which are [documented here](https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/sharing-workflows-with-your-organization).

I was wondering if there is any documentation of the properties.json files you're using in this project, or at least have a reference to some source code which consumes it? I'm building a tool for generating documentation out of my company's repo of shared Azure Pipelines YAML templates and these seem like a good way for adding necessary metadata.

Thanks!

**Comment by andy-mishechkin** [comment]
Hello, @blake-mealey 
As far as I know, now we have no any description of `template-name.properties.json` files. 
We plan to create this documentation in foreseeable future, and place it in azure-pipelines-yaml repo. 
Thank you for your note!

**Comment by blake-mealey** [comment]
Thanks for the response.

FYI here's my docs generation tool: https://www.npmjs.com/package/@pipelinedoc/cli

AS you can see, I took inspiration from your format but adapted it to my needs.

**Comment by scherer-michael** [comment]
Hi there !
I am really sorry to re-open this issue after so much time, but I am not finding any information about those "template-name.properties.json" files.
I tried in the "design" folder, the Developper Community forum, even google-ing around, but nothing.
I understand that those file must introduce runtime parameters for yaml pipelines, but, as I tried to create my own properties.json, commit and pushed it next to my pipeline.yaml, I understood I was doing something wrong as it properly did not work at all.
Can I ask for guidance on the matter, please ?
Thanks in advance !
