### ISSUE TITLE
Blue Green deployment strategy

### ISSUE THREAD

**Issue by serxansherif** [microsoft/azure-pipelines-yaml#531]
Hello,

I get the following error when I use the Blue/Green strategy.

![image](https://user-images.githubusercontent.com/53265420/108820576-6ea53b80-75cd-11eb-8b3f-1ff0d8ed7efc.png)

**Comment by andy-mishechkin** [comment]
Hello, @serxansherif 
Did you mean Azure DevOps yaml scheme ?
https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema%2Cparameter-schema - here I see no any "blueGreen" keywords for strategies. `Parallel, matrix, maxParallel` only.
![image](https://user-images.githubusercontent.com/57713077/115261080-60dee300-a144-11eb-82b5-45f99936fa67.png).
Please clarify, where did you try to use your yaml file, and if it's possible, please provide link to definition of this yaml
Thank you!

**Comment by serxansherif** [comment]
Hello @andy-mishechkin 

According to the following link, Blue green deployment strategy can be used in the yaml pipeline.

https://github.com/microsoft/azure-pipelines-yaml/blob/master/design/deployment-strategies.md

**Comment by anatolybolshakov** [comment]
Hi @serxansherif blue-green strategy is obsolete at the moment - you can find list of available strategies in [docs](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/deployment-jobs?view=azure-devops).
I created PR for this - https://github.com/microsoft/azure-pipelines-yaml/pull/541
