### ISSUE TITLE
Dynamically determine repository resources

### ISSUE THREAD

**Issue by sebastianbirk** [microsoft/azure-pipelines-yaml#537]
We have a design where we want to share one pipeline repository (e.g. test_repo_0) that contains our ADO pipelines among multiple model repositories (e.g. test_repo_1 and test_repo_2) with a multi-repository checkout strategy. The model repository that needs to be checked out to the ADO agent has to be determined dynamically. For the checkout steps we can do that using parameters (specifying either test_repo_1 or test_repo_2).

![image](https://user-images.githubusercontent.com/34235961/117347190-0ca86280-aea9-11eb-978a-bbc136c0efe1.png)

However, for the repository resources we did not find a way to do that dynamically. Instead we have to hardcode all the repositories. Is there a good way to parameterize this? Our problem is that this approach is not very scalable and we want to roll it out to a huge user base.

![image](https://user-images.githubusercontent.com/34235961/117348596-ad4b5200-aeaa-11eb-819e-3c51d2d3912c.png)

**Comment by FlorianPydde** [comment]
Hi, 

We are also facing this issue. We want to restrict users to only be able to run a pipeline but not modify it. The later pipeline will have to pick up some code/configs from another repo where the client pushes all the code. Is there a way to specify the repo name dynamically without listing the repo in the "resources" variables (like the one provided above) ?

**Comment by sebastianbirk** [comment]
Hi @anatolybolshakov thanks for the hint. How can we get a list of all repositories in the ADO project to loop over? Because that is what would be needed for the 'each' expression, right? We want to add all repositories that are in the ADO project to the repository resources section of the pipeline.

**Comment by anatolybolshakov** [comment]
@sebastianbirk I'm not sure if it's possible at the moment to retrieve it from variable - you can only specify it as list above.
This repo is mostly for yaml templates - if you want this as a new feature - please feel free to open a ticket on https://developercommunity.visualstudio.com/search?space=21

**Comment by FlorianPydde** [comment]
@anatolyboshakov thanks for providing the link for the feature request.

**Comment by anatolybolshakov** [comment]
@FlorianPydde feel free to open ticket on https://developercommunity.visualstudio.com/search?space=21
Let me close this one since it's not related to yaml templates provided in this repo.
