### ISSUE TITLE
Learning

### ISSUE THREAD

**Issue by eddie8balltoliver** [microsoft/azure-pipelines-yaml#557]
This repo is for working in the open on Azure Pipelines YAML features. It's not a great place to make [new feature requests](https://developercommunity.visualstudio.com/spaces/21/index.html), [report problems](https://developercommunity.visualstudio.com/spaces/21/index.html), or [get support](https://azure.microsoft.com/en-us/support/devops/). Issues you open here may sit unreviewed for a very long time.

**Comment by anatolybolshakov** [comment]
Hi @eddie8balltoliver yes, this repo is mostly for the issues or feature requests related to the YAML templates presented in the repo.
To get support for YAML editor or other server-side features, or submit a feature request - please reach out to the https://developercommunity.visualstudio.com/search?space=21.
Please let us know if you have any other questions.
