### ISSUE TITLE
#free

### ISSUE THREAD

**Issue by eddie8balltoliver** [microsoft/azure-pipelines-yaml#558]
https://github.com/lapce/lapce/issues/56#issue-1096953775

**Comment by anatolybolshakov** [comment]
Hi @eddie8balltoliver could you please elaborate your request? Do you experience some issue with YAML pipelines templates?

**Comment by anatolybolshakov** [comment]
@eddie8balltoliver I'm closing this due to the lack of details - please fee free to ask any further questions.
