### ISSUE TITLE
New Pipeline resource variable 'resources.pipeline.<Alias>.requestedForEmail'

### ISSUE THREAD

**Issue by kandula-aswin** [microsoft/azure-pipelines-yaml#559]
We have a Pipeline A (CI) that is triggered from a commit to Azure Repo.

In the pipeline we can print the following [Pre-defined variables](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables)

```CI
pool:
  vmImage: 'ubuntu-latest'
steps:
- bash: |
    echo "Requested User: $(Build.RequestedFor)"
    echo "Requested Email: $(Build.RequestedForEmail)"
  displayName: 'Print email'
```
Output:
```
"Requested User: Adb Def"
"Requested Email: abc.def@example.com"
```
Subsequently we Pipeline B (CD) triggered by a `pipelines` resource. It has a set of [Pipeline resource variables](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/resources)

```CD
trigger: none
resources:
  pipelines:
  - pipeline: build
    source: CiPipeline
    trigger:
      branches:
        include:
        - '*'
pool:
  vmImage: 'ubuntu-latest'
steps:
- bash: |
    echo "Requested User: $(resources.pipeline.build.RequestedFor)"
    echo "Requested Email: $(resources.pipeline.build.RequestedForEmail)"
  displayName: 'Print email'
```
Output:
```
"Requested User: Adb Def"
"Requested Email: $(resources.pipeline.build.RequestedForEmail)"
```
Can `resources.pipeline.build.RequestedForEmail` be pre-populated with `Build.RequestedForEmail` value?

**Comment by EzzhevNikita** [comment]
Hi @kandula-aswin this repo is mostly for yaml templates support located in this repo - for any questions regarding Azure DevOps I would suggest to open ticket on https://developercommunity.visualstudio.com/search?space=21 to get right eyes on it.

**Comment by kandula-aswin** [comment]
Thank you @EzzhevNikita, along with Pipelines template, resources too is core yaml
https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema

I have taken your advice and submitted a question here too 
https://developercommunity.visualstudio.com/t/Missing-Pipeline-resource-variable-reso/1654282

**Comment by EzzhevNikita** [comment]
@kandula-aswin Let me close the item in this repo since we have you have created it in the developer community.
