### ISSUE TITLE
Support for if-else runtime condition evaluation

### ISSUE THREAD

**Issue by tapika** [microsoft/azure-pipelines-yaml#576]
Currently if you want to get compile time if-else evaluation - you can do something like this:

```
variables:
   VERBOSE_FLAG:
   ${{if variables['System.Debug']}}:
      value: '--verbose'
   ${{else}}:
      value: ''
```

if you want to have runtime if-else evaluation - then it's not possible directly, but possible to make it indirectly:

https://stackoverflow.com/a/67198023/2338477

using `replace` function two times.

It would be nice if yaml would support directly function like:

`if(<condition>, <then case> <else case>)`

for runtime condition evaluation.

**Comment by DmitriiBobreshev** [comment]
@tapika, hello again :), thanks for the suggestion. This repo is used for some questions about YAML examples and problems that you may encounter in the course of your work. To request some features for more convenient use you can post this suggestion to [the Developer Community](https://developercommunity.visualstudio.com/home). Sorry for the late response
