### ISSUE TITLE
Possibility to use runtime variables as a template argument

### ISSUE THREAD

**Issue by tapika** [microsoft/azure-pipelines-yaml#578]
By default yaml does permit use of compile time variables in conditions.

For example:

```
   -   template: mytemplate.yml
       parameters:
            param1: ${{parameters.param1}}
```

this syntax is supported.

But this syntax is not supported:

```
   -   template: mytemplate.yml
       parameters:
            param1: $(variables.param1)
```

According to following web page:

https://learn.microsoft.com/en-us/azure/devops/pipelines/process/runtime-parameters?view=azure-devops&tabs=script

> Parameters are only available at template parsing time. Parameters are expanded just before the pipeline runs so that values surrounded by ${{ }} are replaced with parameter values. Use [variables](https://learn.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops) if you need your values to be more widely available during your [pipeline run](https://learn.microsoft.com/en-us/azure/devops/pipelines/process/runs?view=azure-devops).

Which suggests that using runtime variables as a template parameters is not possible.

Would it be possible to add such support ?

**Comment by guidooliveira** [comment]
I would really love this feature, and/or possibly a way to pass arrays or objects as stringified JSON, just like we do for matrix.

**Comment by DmitriiBobreshev** [comment]
Hi @tapika, thank you for the suggestion and sorry for the late response, this repo is used for some questions about YAML examples and problems that you may encounter in the course of work. To request some features for more convenient use or report about the issue you can post this suggestion to [the Developer Comunity](https://developercommunity.visualstudio.com/home)
