### ISSUE TITLE
by design there´s not available option in DeVops Service to create a new pipeline yaml for "existing" branch 

### ISSUE THREAD

**Issue by msdansau** [microsoft/azure-pipelines-yaml#585]
I have a sample DevOps service organization which have 1 project which have 1 repository with 3 branches (which have the same cloned code which  have some modifications each)
 
![image](https://user-images.githubusercontent.com/92469585/225466762-52484dbb-7e97-4098-991a-4d54a2f7b0d1.png)

I then  created a simple pipeline in main branch  to compile the net core code, but I want to use from the same pipeline another branch  such as “testing”.  and unfortunatelly the only way to achieve this is copy and paste the created yaml file from master to existing branch so that the CI triger takes effect when there´s a change in branch such yaml can be trigered.

why there´s not any available option in devops service portal when creating a new pipeline to choose to which BRANCH it should be created for existing branches????

Build pipeline..
 
![image](https://user-images.githubusercontent.com/92469585/226111285-e331b63c-32da-4fc9-b782-30ec4452bacb.png)

if you happen to see an available option or technic please let me know .Any sample or help for this would be appreciated. it looks like by desing which in not right or practical having to create it in master branch each pipeline and then copy and paste it to each "existing" branches  and modify the triger instead of master to the respective branch.

**Comment by sergey-koryshev** [comment]
Hi @msdansau, as far as understand your question, you want to checkout multiple branches. Please follow this guide to achieve this: https://learn.microsoft.com/en-us/azure/devops/pipelines/repos/multi-repo-checkout?view=azure-devops

**Comment by msdansau** [comment]
@sergey-koryshev  thank you so much for your help and sharing this link. Yes I saw it, but i fail to use the pipeline to checkout other branches of the same devops git repository.   the only solution i found is to copy the mybuild.yaml into all the branches and run each manually.   is there a way to run a build  defined in master branch to run the code of another branch (without having to paste the same .yaml in the branch) ?

**Comment by sergey-koryshev** [comment]
Yes, you are right, this pipeline architecture is by design. You create one pipeline and then you can manage triggers to be able to run this pipeline against any branches but the branches should have related YAML-files. You can reduce duplicated YAML-code by using external repository to store it and then in target branches you can just checkout the YAML-repository and include related YAML-templates or something like this. 

Actually this repository is wrong place for such type of request. Could you please create a ticket on https://developercommunity.visualstudio.com ?

**Comment by msdansau** [comment]
thank you we can close it now. i´ll request a "request feature" to MS engineering team so that they can add an option into the new pipeline wizard to choose which branch to create the pipeline (yaml file).   much appreciated.
