### ISSUE TITLE
how to triger a build pipeline from powershell

### ISSUE THREAD

**Issue by msdansau** [microsoft/azure-pipelines-yaml#588]
Hi folks i urgently need to know if it is posible to triger any build pipeline in azure devops service from windows powershell in my machine.  if so, please kindly paste the steps or share any online documentation so that i can catch up on it.

if this is not posible by design. Could you please at least indicate if this is posible to achieve from another pipeline using powershell task? share doc please.
thanks in advance.

**Comment by DmitriiBobreshev** [comment]
Hi @msdansau, Thanks for the question. It's not possible from PowerShell directly, but you can use [tfx-cli](https://www.npmjs.com/package/tfx-cli) for it with tfx build command(see tfx build queue -help output for details).

**Comment by msdansau** [comment]
@DmitriiBobreshev   thanks a lot. that answer my concern. much appreciated!.
