### ISSUE TITLE
Pipeline resource trigger documentation missing prerequisite 

### ISSUE THREAD

**Issue by abelmokadem** [microsoft/azure-pipelines-yaml#590]
There is some documentation about how a pipeline can trigger another pipeline. However, it is nowhere documented that this pipeline file should be present in the main branch in order for this trigger to work. It would be helpful for the next person if there is a big banner that mentions this.

**Comment by DenisRumyantsev** [comment]
@abelmokadem thanks for reporting this! We will check our documentation about pipeline triggers and update it.
