### ISSUE TITLE
Custom expression/function in Yaml

### ISSUE THREAD

**Issue by FreesonM3as** [microsoft/azure-pipelines-yaml#601]
Hope to be able to provide a custom function in yaml by a Azure DevOps Extension contribution point. 
For example:

```
- template: sometemplate.yaml
  parameters:
     parameterContext: ${{ merge(parameters.parameterContext, convertFromJson('{"dryRun":true}') ) }}
``` 
where `merge` and `convertFromJson` are custom functions.

**Comment by max-zaytsev** [comment]
Please post your suggestion on [the Developer Community](https://developercommunity.visualstudio.com/home) to get the right eyes on it, since this repo is mostly for questions about templates located in this repo.
