### ISSUE TITLE
Cannot use Github App on multiple projects for the same organization

### ISSUE THREAD

**Issue by rauljmz** [microsoft/azure-pipelines-yaml#84]
I am trying to use the GitHub App authentication in multiple projects for the same organization.

I have created a project using the GitHub App (which is installed in GitHub giving access to **all** repos in the organization). This works fine as expected.
However, when I create another (a second) new project, I am prompted to use OAuth:
![image](https://user-images.githubusercontent.com/1165232/50091298-e368d800-0202-11e9-8b09-dd79727f88d1.png)
If I click on the other option ```Install our app from the GitHub Marketplace``` I am redirected to the GitHub App page:
![image](https://user-images.githubusercontent.com/1165232/50091372-1b701b00-0203-11e9-9392-d1784205cae7.png)
Where I can confirm it is installed, and enabled for all repositories.

**Expected behaviour**
I would expect Azure Pipelines to give me a list of all my repositories when creating a new project.
According to the [documentation](https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/github?view=vsts#install-the-github-app):

> The app will become Azure Pipelines’ default method of authentication to GitHub (instead of OAuth) when organization members create pipelines for their repositories. This is recommended so that pipelines run as “Azure Pipelines” instead of a user’s GitHub identity which may lose access to the repository.

**Comment by haodeon** [comment]
This is one of the first search results for this issue.

The solution is to share the service connection across projects.
