### ISSUE TITLE
template parameter substitution in scripts fail if script length > 2000

### ISSUE THREAD

**Issue by afeblot** [microsoft/azure-pipelines-yaml#86]
The following works nicely, except if the script length is larger than 2000 chars. Some of us need such long scripts :-) 
```
    - bash: |
        if [ '${{parameters.some_param}}' == true ]; then
          do_something
        fi
```

With larger scripts, the build fails at the template substitution step with the following message:

   azure-pipelines.yml (Line: xxx, Col: yyy): Exceeded max expression length 2000. For more help, refer to https://go.microsoft.com/fwlink/?linkid=842996

**Comment by wichert** [comment]
I'm guessing this is related to #59 ?
