### ISSUE TITLE
On github's branch protection page Azure Pipelines isn't labeled as such

### ISSUE THREAD

**Issue by ry** [microsoft/azure-pipelines-yaml#89]
<img width="738" alt="screen shot 2018-12-21 at 1 03 26 pm" src="https://user-images.githubusercontent.com/80/50356690-f5a78680-0520-11e9-98f5-186d12201608.png">

Here pipelines is displayed as "denoland.deno_std"

**Comment by TingluoHuang** [comment]
@madhurig for github integration problem.

**Comment by madhurig** [comment]
@ry - Thanks for your feedback. With Azure pipelines we use the name of the pipeline as the name of the status check and don't add the "Azure Pipelines" branding. 

- We optimize for the way checks are shown on the Pull requests. GitHub already shows the icon and GitHub app name and organizes all checks under that. 

![image](https://user-images.githubusercontent.com/3269636/50611828-d1936000-0ea5-11e9-966f-b57355efbe1a.png)

![image](https://user-images.githubusercontent.com/3269636/50611803-b7f21880-0ea5-11e9-9176-0385750ad744.png)

- Multiple azure pipelines may be setup for the same repository. The pipeline name can be customized by the pipeline owners in Azure Pipelines. Matching the GitHub status name to the Azure pipeline name, allows users to change it as desired. In your case, you can update the pipeline name to include "Azure Pipelines" if you wish. 

Thanks,
Madhuri
